### ISSUE TITLE
The name field of PeriodicTask does not supports Chinese characters

### ISSUE THREAD

**Issue by iTraceur** [celery/django-celery-beat#10]
celery beat v4.0.0 (latentcall) is starting.
__    -    ... __   -        _
LocalTime -> 2016-11-18 20:30:01
Configuration ->
    . broker -> redis://localhost:6379/0
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> django_celery_beat.schedulers.DatabaseScheduler

    . logfile -> [stderr]@%DEBUG
    . maxinterval -> 5.00 seconds (5s)
[2016-11-18 20:30:01,155: DEBUG/MainProcess] DatabaseScheduler: initial read
[2016-11-18 20:30:01,155: INFO/MainProcess] Writing entries...
[2016-11-18 20:30:01,156: DEBUG/MainProcess] DatabaseScheduler: Fetching database schedule
[2016-11-18 20:30:01,163: WARNING/MainProcess] Traceback (most recent call last):
[2016-11-18 20:30:01,163: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/bin/celery", line 11, in <module>
[2016-11-18 20:30:01,164: WARNING/MainProcess] sys.exit(main())
[2016-11-18 20:30:01,164: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
[2016-11-18 20:30:01,165: WARNING/MainProcess] _main()
[2016-11-18 20:30:01,165: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
[2016-11-18 20:30:01,166: WARNING/MainProcess] cmd.execute_from_commandline(argv)
[2016-11-18 20:30:01,166: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
[2016-11-18 20:30:01,166: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2016-11-18 20:30:01,167: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/base.py", line 278, in execute_from_commandline
[2016-11-18 20:30:01,171: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2016-11-18 20:30:01,171: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
[2016-11-18 20:30:01,176: WARNING/MainProcess] return self.execute(command, argv)
[2016-11-18 20:30:01,176: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
[2016-11-18 20:30:01,177: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2016-11-18 20:30:01,177: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/base.py", line 282, in run_from_argv
[2016-11-18 20:30:01,177: WARNING/MainProcess] sys.argv if argv is None else argv, command)
[2016-11-18 20:30:01,177: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/base.py", line 365, in handle_argv
[2016-11-18 20:30:01,177: WARNING/MainProcess] return self(*args, **options)
[2016-11-18 20:30:01,178: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/base.py", line 241, in __call__
[2016-11-18 20:30:01,178: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2016-11-18 20:30:01,178: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/bin/beat.py", line 107, in run
[2016-11-18 20:30:01,179: WARNING/MainProcess] return beat().run()
[2016-11-18 20:30:01,179: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/apps/beat.py", line 79, in run
[2016-11-18 20:30:01,180: WARNING/MainProcess] self.start_scheduler()
[2016-11-18 20:30:01,181: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/apps/beat.py", line 107, in start_scheduler
[2016-11-18 20:30:01,182: WARNING/MainProcess] service.start()
[2016-11-18 20:30:01,182: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/beat.py", line 528, in start
[2016-11-18 20:30:01,186: WARNING/MainProcess] humanize_seconds(self.scheduler.max_interval))
[2016-11-18 20:30:01,186: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
[2016-11-18 20:30:01,187: WARNING/MainProcess] value = obj.__dict__[self.__name__] = self.__get(obj)
[2016-11-18 20:30:01,187: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/beat.py", line 572, in scheduler
[2016-11-18 20:30:01,187: WARNING/MainProcess] return self.get_scheduler()
[2016-11-18 20:30:01,187: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/beat.py", line 567, in get_scheduler
[2016-11-18 20:30:01,188: WARNING/MainProcess] lazy=lazy,
[2016-11-18 20:30:01,188: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 179, in __init__
[2016-11-18 20:30:01,188: WARNING/MainProcess] Scheduler.__init__(self, *args, **kwargs)
[2016-11-18 20:30:01,189: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/celery/beat.py", line 204, in __init__
[2016-11-18 20:30:01,189: WARNING/MainProcess] self.setup_schedule()
[2016-11-18 20:30:01,189: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 187, in setup_schedule
[2016-11-18 20:30:01,189: WARNING/MainProcess] self.install_default_entries(self.schedule)
[2016-11-18 20:30:01,189: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 283, in schedule
[2016-11-18 20:30:01,189: WARNING/MainProcess] repr(entry) for entry in values(self._schedule)),
[2016-11-18 20:30:01,189: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 283, in <genexpr>
[2016-11-18 20:30:01,189: WARNING/MainProcess] repr(entry) for entry in values(self._schedule)),
[2016-11-18 20:30:01,189: WARNING/MainProcess] File "/home/david/PycharmProjects/david_blog/env/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 162, in __repr__
[2016-11-18 20:30:01,190: WARNING/MainProcess] safe_repr(self.kwargs), self.schedule,
[2016-11-18 20:30:01,190: WARNING/MainProcess] UnicodeDecodeError
[2016-11-18 20:30:01,190: WARNING/MainProcess] :
[2016-11-18 20:30:01,190: WARNING/MainProcess] 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
[2016-11-18 20:30:01,190: INFO/MainProcess] Writing entries...

**Comment by mheppner** [comment]
Can you give more details of how to reproduce this? What is your task named? Python version?

**Comment by iTraceur** [comment]
When I add a periodic task which name called "统计访问人数" in django admin, the issue occurred. python verson: 2.7.11, django verson: 1.9.7
