### ISSUE TITLE
'bytes' object has no attribute 'encode' when running with python 3.4

### ISSUE THREAD

**Issue by t-io** [celery/django-celery-beat#11]
when starting celery like this `celery worker -E -B -Q celery -A myapp -S django`
I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 278, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 241, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/worker.py", line 139, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 214, in apply
    step.include(parent)
  File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 343, in include
    return self._should_include(parent)[0]
  File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 339, in _should_include
    return True, self.create(parent)
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/components.py", line 214, in create
    w._persistence = w.state.Persistent(w.state, w.statedb, w.app.clock)
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/state.py", line 189, in __init__
    self.merge()
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/state.py", line 197, in merge
    self._merge_with(self.db)
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/state.py", line 213, in _merge_with
    self._merge_revoked(d)
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/state.py", line 232, in _merge_revoked
    self._merge_revoked_v3(d[b'zrevoked'])
  File "/usr/lib/python3.4/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
AttributeError: 'bytes' object has no attribute 'encode'
```

without `-S django`option it works fine.

**Comment by powellc** [comment]
I get this same error on Python 3.5.2 :(

**Comment by jroblak** [comment]
It seems to be related to embedding the beat scheduler `-B` combined with `-S`

**Comment by mheppner** [comment]
Can you try running celery beat separately from the worker? Eg, `celery beat -A myapp -S django`.

**Comment by jroblak** [comment]
Yes, that works. I'm only able to reproduce when using both the `-B` and `-S` flags.

**Comment by mheppner** [comment]
I'd report that on the main celery repo. In v4, they changed from [optparse to argparse](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#programs), so it's probably related to that and not with `django-celery-beat`.
