### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'localize'

### ISSUE THREAD

**Issue by muhtarcanrb** [celery/django-celery-beat#132]
django-celery-beat==1.1.1

```
2018-02-26 18:26:25,989 - CRITICAL - celery.beat:111 - beat raised exception <type 'exceptions.AttributeError'>: AttributeError("'NoneType' object has no attribute 'localize'",)
Traceback (most recent call last):
  File "/opt/app/lib/python2.7/site-packages/celery/apps/beat.py", line 107, in start_scheduler
    service.start()
  File "/opt/app/lib/python2.7/site-packages/celery/beat.py", line 528, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/opt/app/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/app/lib/python2.7/site-packages/celery/beat.py", line 572, in scheduler
    return self.get_scheduler()
  File "/opt/app/lib/python2.7/site-packages/celery/beat.py", line 567, in get_scheduler
    lazy=lazy,
  File "/opt/app/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 183, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/opt/app/lib/python2.7/site-packages/celery/beat.py", line 204, in __init__
    self.setup_schedule()
  File "/opt/app/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 191, in setup_schedule
    self.install_default_entries(self.schedule)
  File "/opt/app/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 290, in schedule
    self._schedule = self.all_as_schedule()
  File "/opt/app/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 199, in all_as_schedule
    s[model.name] = self.Entry(model, app=self.app)
  File "/opt/app/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 88, in __init__
    model.last_run_at = self._default_now()
  File "/opt/app/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 106, in _default_now
    return now.tzinfo.localize(now.replace(tzinfo=None))
AttributeError: 'NoneType' object has no attribute 'localize'
```

**Comment by hazzadous** [comment]
Having the same issue here with django-celery-beat==1.1.1 , resolved with downgrade django-celery-beat==1.1.0 on preliminary exploration.

**Comment by sirkonst** [comment]
Have same problem :-(

**Comment by wrdeman** [comment]
I got the same issue and after a bit of digging found that the version of celery needs to be >=4.1.0.

**Comment by YashAgarwal** [comment]
I am getting the same error, with python 3.7
```
django-celery-results==1.0.4
  - celery [required: >=4.0,<5.0, installed: 4.2.1]
    - billiard [required: >=3.5.0.2,<3.6.0, installed: 3.5.0.5]
    - kombu [required: >=4.2.0,<5.0, installed: 4.2.2]
      - amqp [required: >=2.1.4,<3.0, installed: 2.3.2]
        - vine [required: >=1.1.3, installed: 1.1.4]
    - pytz [required: >dev, installed: 2018.5]
```

**Comment by jshields** [comment]
Having this issue on latest of both packages:
```
celery==4.4.2
django-celery-beat==2.0.0
```

**Comment by ennioferreirab** [comment]
> Having this issue on latest of both packages:
> 
> ```
> celery==4.4.2
> django-celery-beat==2.0.0
> ```

Same here 
`celery==4.4.7
django-celery-beat==2.0.0`

solve downgrade django-celery-beat==1.1.0

**Comment by salykin** [comment]
Same here:
```celery==4.4.7 django-celery-beat==1.6.0 pytz==2021.1 python=2.7.13```

For my case next setting solves the issue without downgrading to 1.1.0:
```DJANGO_CELERY_BEAT_TZ_AWARE = False```
(as described in https://github.com/celery/django-celery-beat/issues/80#issuecomment-681735535)
