### ISSUE TITLE
Should Celery Beat start without database tables?

### ISSUE THREAD

**Issue by craiga** [celery/django-celery-beat#165]
If you start Celery Beat with django_celery_beat's DatabaseScheduler before running migrations, you get an error:

    celery beat v4.2.1 (windowlicker) is starting.
    /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
      """)
    __    -    ... __   -        _
    LocalTime -> 2018-10-05 12:14:41
    Configuration ->
        . broker -> amqp://env-mgmt-dashboard:**@rabbitmq:5672//
        . loader -> celery.loaders.app.AppLoader
        . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
    
        . logfile -> [stderr]@%INFO
        . maxinterval -> 5.00 seconds (5s)
    beat: Starting...
    Writing entries...
    beat raised exception <class 'django.db.utils.ProgrammingError'>: ProgrammingError('relation "django_celery_beat_periodictask" does not exist\nLINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...\n                                                             ^\n',)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
        return obj.__dict__[self.__name__]
    KeyError: 'scheduler'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
        return self.cursor.execute(sql, params)
    psycopg2.ProgrammingError: relation "django_celery_beat_periodictask" does not exist
    LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...
                                                                 ^
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
        service.start()
      File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 579, in start
        humanize_seconds(self.scheduler.max_interval))
      File "/usr/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
        value = obj.__dict__[self.__name__] = self.__get(obj)
      File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 623, in scheduler
        return self.get_scheduler()
      File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 618, in get_scheduler
        lazy=lazy,
      File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 183, in __init__
        Scheduler.__init__(self, *args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 225, in __init__
        self.setup_schedule()
      File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 191, in setup_schedule
        self.install_default_entries(self.schedule)
      File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 290, in schedule
        self._schedule = self.all_as_schedule()
      File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 197, in all_as_schedule
        for model in self.Model.objects.enabled():
      File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
        self._fetch_all()
      File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
        self._result_cache = list(self._iterable_class(self))
      File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
        results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
      File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
        cursor.execute(sql, params)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
        return super().execute(sql, params)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
        return executor(sql, params, many, context)
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "django_celery_beat_periodictask" does not exist
    LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...
                                                                 ^
    
    Writing entries...

You could argue this is fair enough, but it's not a great experience for users starting Celery Beat as part of Docker Compose (I quite often run `docker-compose up` before running `migrate`, and I don't think I'm alone in this).

I'd expect this to be handled in a similar way to what happens when the broker isn't present: when the schedule fails to load, a message is logged, and loading the schedule is retried later on.

[I've made a start on a fix for this](https://github.com/celery/django-celery-beat/compare/master...craiga:handle-database-error-getting-schedule#diff-b75d080f084c75edb1046bcac05d0d12) by catching database errors in `all_as_schedule`:

    def all_as_schedule(self):
        debug('DatabaseScheduler: Fetching database schedule')
        s = {}
        try:
            for model in self.Model.objects.enabled():
                try:
                    s[model.name] = self.Entry(model, app=self.app)
                except ValueError:
                    pass
        except DatabaseError as exc:
            logger.exception('Database gave error: %r', exc)
        return s

This works reasonably well, but breaks installing default entries. I also imagine there needs to be tests.

If there's interest in this feature, I'd love some guidance on what the best way to implement it would be.

**Comment by syurchenko** [comment]
It is a problem of every django application which starts without ready database.
Purely this problem cab be solved by adding wait script before running celery-beat and other applications.
https://github.com/vishnubob/wait-for-it
in my run_celery.sh:
```
#!/usr/bin/env bash

set -e

/wait-for-it.sh $PG_HOST:$PG_PORT --timeout=10 --strict -- echo "postgres is up"

celery -E -A project worker -l info --autoscale=10,2 -Q my_queue -n worker -B
```
in docker-compose:
```
  my_service:
    image: some_image
    command: "/run_celery.sh"
```

**Comment by craiga** [comment]
Thanks for the feedback, @syurchenko

As far as I understand it, `wait-for-it` will only wait for Postgres to become available. If the table doesn't exist, Celery Beat will still die afterwards.

Django and Celery Beat handle missing database tables quite differently.

Django will start up just fine, but will report an error whenever something tries to access that table, but it will keep running.

Celery Beat fails to start. It raises an unhandled error and it exits immediately.

**Comment by thedrow** [comment]
Unfortunately if you want to maintain your schedule using this extension you have to run the migrations before everything else.

**Comment by dontic** [comment]
@craiga super late to the game, but I implemented a similar thing to what @sergei-iurchenko sugested but, in my case, it waits for my django instance to be pingable (which only happens one it has gone through all the migrations and set up):

`wait-for-it.sh` can be found here: https://github.com/vishnubob/wait-for-it/tree/master

This is my `entrypoint-beat.sh` for my docker compose:
```
#!/bin/sh

until cd /app/backend
do
    echo "Waiting for server volume..."
done

# Wait for the backend to be ready before starting celery by using wait-for-it.sh
/app/backend/wait-for-it.sh backend:8000 --timeout=90 -- echo "The backend is up"

# run celery beat
echo "Starting celery beat..."
celery -A core beat -l info

```
