### ISSUE TITLE
Migration rename leads to a dependency error when upgrading

### ISSUE THREAD

**Issue by nikolaik** [celery/django-celery-beat#177]
Migration with sequence number 0006 [0006_auto_20180210_1226](https://github.com/celery/django-celery-beat/blob/v1.1.1/django_celery_beat/migrations/0006_auto_20180210_1226.py) in v1.1.1 was renamed to [0006_auto_20180322_0932](https://github.com/celery/django-celery-beat/blob/v1.2.0/django_celery_beat/migrations/0006_auto_20180322_0932.py) in v1.2.0 (and the contents changed).

This causes the following error with our own migrations pointing to the v1.1.1 migration.
```
django.db.migrations.exceptions.NodeNotFoundError: Migration myapp.0001_initial dependencies reference nonexistent parent node ('django_celery_beat', '0006_auto_20180210_1226')
```

What was the reasoning behind renaming the migration instead of creating a new one? #99 introduced the renamed migration.
Since this change was introduced in a semver wise non breaking version bump, should we create a fix for this, restoring the old 0006 migration and adding the new migrations since v1.1.1 from 0007 and onward?

**Comment by rsichny** [comment]
@mathiasose still fails when updating from 1.1.1 to latest master:
1. `pip install django-celery-beat==1.1.1`
2. `python manage.py migrate` (no errors)
3. `pip install -U https://github.com/celery/django-celery-beat/zipball/master#egg=django-celery-beat`
4. `python manage.py migrate`

```
(0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
2018-10-13 12:28:54,883 DEBUG (0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT %s NOT NULL; (params ['UTC'])
2018-10-13 12:28:54,891 DEBUG ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT %s NOT NULL; (params ['UTC'])
(0.039) ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT 'UTC' NOT NULL; args=['UTC']
2018-10-13 12:28:54,930 DEBUG (0.039) ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT 'UTC' NOT NULL; args=['UTC']
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "timezone" DROP DEFAULT; (params [])
2018-10-13 12:28:54,931 DEBUG ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "timezone" DROP DEFAULT; (params [])
(0.000) ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "timezone" DROP DEFAULT; args=[]
2018-10-13 12:28:54,931 DEBUG (0.000) ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "timezone" DROP DEFAULT; args=[]
(0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
2018-10-13 12:28:54,944 DEBUG (0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('django_celery_beat', '0006_auto_20180322_0932', '2018-10-13T12:28:54.945126+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('django_celery_beat', '0006_auto_20180322_0932', datetime.datetime(2018, 10, 13, 12, 28, 54, 945126, tzinfo=<UTC>))
2018-10-13 12:28:54,945 DEBUG (0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('django_celery_beat', '0006_auto_20180322_0932', '2018-10-13T12:28:54.945126+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('django_celery_beat', '0006_auto_20180322_0932', datetime.datetime(2018, 10, 13, 12, 28, 54, 945126, tzinfo=<UTC>))
  Applying django_celery_beat.0006_auto_20180322_0932... OK
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "one_off" boolean DEFAULT %s NOT NULL; (params [False])
2018-10-13 12:28:54,949 DEBUG ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "one_off" boolean DEFAULT %s NOT NULL; (params [False])
(0.057) ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "one_off" boolean DEFAULT false NOT NULL; args=[False]
2018-10-13 12:28:55,007 DEBUG (0.057) ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "one_off" boolean DEFAULT false NOT NULL; args=[False]
ALTER TABLE "django_celery_beat_periodictask" ALTER COLUMN "one_off" DROP DEFAULT; (params [])
2018-10-13 12:28:55,007 DEBUG ALTER TABLE "django_celery_beat_periodictask" ALTER COLUMN "one_off" DROP DEFAULT; (params [])
(0.000) ALTER TABLE "django_celery_beat_periodictask" ALTER COLUMN "one_off" DROP DEFAULT; args=[]
2018-10-13 12:28:55,007 DEBUG (0.000) ALTER TABLE "django_celery_beat_periodictask" ALTER COLUMN "one_off" DROP DEFAULT; args=[]
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "start_time" timestamp with time zone NULL; (params [])
2018-10-13 12:28:55,012 DEBUG ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "start_time" timestamp with time zone NULL; (params [])
(0.000) ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "start_time" timestamp with time zone NULL; args=[]
2018-10-13 12:28:55,012 DEBUG (0.000) ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "start_time" timestamp with time zone NULL; args=[]
(0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
2018-10-13 12:28:55,036 DEBUG (0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
(0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('django_celery_beat', '0007_auto_20180521_0826', '2018-10-13T12:28:55.037696+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('django_celery_beat', '0007_auto_20180521_0826', datetime.datetime(2018, 10, 13, 12, 28, 55, 37696, tzinfo=<UTC>))
2018-10-13 12:28:55,038 DEBUG (0.001) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('django_celery_beat', '0007_auto_20180521_0826', '2018-10-13T12:28:55.037696+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('django_celery_beat', '0007_auto_20180521_0826', datetime.datetime(2018, 10, 13, 12, 28, 55, 37696, tzinfo=<UTC>))
  Applying django_celery_beat.0007_auto_20180521_0826... OK
(0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
2018-10-13 12:28:55,059 DEBUG (0.001) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
(0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('django_celery_beat', '0008_auto_20180914_1922', '2018-10-13T12:28:55.060145+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('django_celery_beat', '0008_auto_20180914_1922', datetime.datetime(2018, 10, 13, 12, 28, 55, 60145, tzinfo=<UTC>))
2018-10-13 12:28:55,060 DEBUG (0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('django_celery_beat', '0008_auto_20180914_1922', '2018-10-13T12:28:55.060145+00:00'::timestamptz) RETURNING "django_migrations"."id"; args=('django_celery_beat', '0008_auto_20180914_1922', datetime.datetime(2018, 10, 13, 12, 28, 55, 60145, tzinfo=<UTC>))
  Applying django_celery_beat.0008_auto_20180914_1922... OK
ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT %s NOT NULL; (params ['UTC'])
2018-10-13 12:28:55,092 DEBUG ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT %s NOT NULL; (params ['UTC'])
(0.001) ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT 'UTC' NOT NULL; args=['UTC']
2018-10-13 12:28:55,093 DEBUG (0.001) ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT 'UTC' NOT NULL; args=['UTC']
  Applying django_celery_beat.0007_auto_20181012_1414...Traceback (most recent call last):
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "timezone" of relation "django_celery_beat_crontabschedule" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 435, in add_field
    self.execute(sql, params)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rs/projects/survey-api/.env/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "timezone" of relation "django_celery_beat_crontabschedule" already exists
```

**Comment by auvipy** [comment]
How about deleting all the old migrations and generating new ones and try?

**Comment by rsichny** [comment]
@auvipy i can't be 100% sure about covering all cases but #183 seems to work just fine
