### ISSUE TITLE
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

### ISSUE THREAD

**Issue by zuoakang** [celery/django-celery-beat#190]
> env
- python3.6
- django_celery_beat==1.2.0

**Every now and then, this same mistake is reported.Please help look at it.**
```python
Traceback (most recent call last):
  File "e:\python_env\test\lib\site-packages\django_celery_beat\schedulers.py", line 262, in sync
    self.schedule[name].save()
  File "e:\python_env\test\lib\site-packages\django_celery_beat\schedulers.py", line 136, in save
    obj = type(self.model)._default_manager.get(pk=self.model.pk)
  File "e:\python_env\test\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "e:\python_env\test\lib\site-packages\django\db\models\query.py", line 397, in get
    num = len(clone)
  File "e:\python_env\test\lib\site-packages\django\db\models\query.py", line 254, in __len__
    self._fetch_all()
  File "e:\python_env\test\lib\site-packages\django\db\models\query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "e:\python_env\test\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "e:\python_env\test\lib\site-packages\django\db\models\sql\compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "e:\python_env\test\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "e:\python_env\test\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "e:\python_env\test\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "e:\python_env\test\lib\site-packages\django\db\backends\utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "e:\python_env\test\lib\site-packages\django\db\backends\base\base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

```

**Comment by picturedots** [comment]
Also encountering this issue after upgrade to django_celery_beat==1.2.0 -- but I was able to make issue go away by moving queries out of a transaction block.

**Comment by picturedots** [comment]
@oortega  I made the transaction block smaller.   This might not be a good solution in all cases.

**before:**

- transaction decorator on method
- method contains queries and writes intermixed

**after:**
```
do all queries...
with transaction.atomic():
    do all writes
```

**Comment by rthille** [comment]
We're seeing these two different tracebacks from a service with django_celery_beat==1.2.0:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django_celery_beat/schedulers.py", line 234, in schedule_changed
    last, ts = self._last_timestamp, self.Changes.last_change()
  File "/usr/local/lib/python3.7/dist-packages/django_celery_beat/models.py", line 240, in last_change
    return cls.objects.get(ident=1).last_update
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django_celery_beat/schedulers.py", line 262, in sync
    self.schedule[name].save()
  File "/usr/local/lib/python3.7/dist-packages/django_celery_beat/schedulers.py", line 136, in save
    obj = type(self.model)._default_manager.get(pk=self.model.pk)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by U-238** [comment]
I am also seeing the same two tracebacks as reported by @rthille above, with django_celery_beat==1.2.0. I have noticed that the problem is temporarily alleviated after the celery.backend_cleanup task has been run, but then recurs again.

**Comment by auvipy** [comment]
could anyone try this with 1.4.0 release?

**Comment by auvipy** [comment]
closing due to lack of feedback. will reopen if not already fixed.
