### ISSUE TITLE
Met an error when using django-celery-beat  psycopg2.InterfaceError: connection already closed

### ISSUE THREAD

**Issue by cherrie12** [celery/django-celery-beat#237]
django-celery-beat: 1.2.0
celery: 4.1
postgressql 11

I met below error when start celery beat and every job will run continually until I kill the beat.

```
[2019-03-29 17:02:20,086: ERROR/MainProcess] Database error while sync: InterfaceError('connection already closed',)
Traceback (most recent call last):
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 234, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 262, in sync
    self.schedule[name].save()
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 303, in schedule
    elif self.schedule_changed():
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 234, in schedule_changed
    last, ts = self._last_timestamp, self.Changes.last_change()
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django_celery_beat/models.py", line 240, in last_change
    return cls.objects.get(ident=1).last_update
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 234, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 234, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
[2019-03-29 17:02:40,152: INFO/MainProcess] DatabaseScheduler: Schedule changed.
[2019-03-29 17:02:40,152: INFO/MainProcess] Writing entries...
[2019-03-29 17:02:40,157: ERROR/MainProcess] Database error while sync: InterfaceError('connection already closed',)
Traceback (most recent call last):
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 234, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/home/ontask/miniconda3/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed
```

**Comment by liquidpele** [comment]
Looks like a pretty old issue... 

https://github.com/celery/django-celery/issues/121

**Comment by auvipy** [comment]
does this persist with the latest release or in master?

**Comment by liquidpele** [comment]
It likely is still there.  We had to account for this in a python daemon we wrote at work...  basically when postgresql is restarted, it takes django a while to realize the connection is dead and sometimes it never resets it.    This is how we basically handle that to kick django.  

```
try:
    run_all_the_main_functionality()
except (db.OperationalError, db.InterfaceError, db.InternalError) as e:
    self.log.error('Caught DB connection error, resetting connection')
    db.close_old_connections()
```

Not sure how to apply that to celery-beat as I haven't looked at the daemon part of the code yet.  If someone wants to take a go at fixing it before I get there then feel free.

**Comment by auvipy** [comment]
closing for lack of feedback.

**Comment by dd84ai** [comment]
if someone would be searching why they have Interface Error: connection already closed due to Django ORM usage in celery task with Celery worker fixture, then there is issue (with some solutions) there about it https://github.com/celery/celery/issues/4511

**Comment by dkoenigroer** [comment]
Same Problem here using Djangop and celery beat:
```python
    task.backend.store_result(
  File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 526, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/usr/local/lib/python3.9/site-packages/django_celery_results/backends/database.py", line 147, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "/usr/local/lib/python3.9/site-packages/django_celery_results/managers.py", line 42, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_celery_results/managers.py", line 164, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
[2024-07-12 03:00:00,277: ERROR/ForkPoolWorker-2] Task x.common.tasks.commando_task[939e2e49-198a-44ea-ad2f-f5749c57164a] raised unexpected: InterfaceError('connection already closed')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 443, in trace_task
    task.backend.store_result(
  File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 526, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/usr/local/lib/python3.9/site-packages/django_celery_results/backends/database.py", line 147, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "/usr/local/lib/python3.9/site-packages/django_celery_results/managers.py", line 42, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_celery_results/managers.py", line 164, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 262, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 256, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

Django==4.0.10
django-celery-beat==2.6.0
django-celery-results==2.5.1
celery==5.4.0
django-redis==5.4.0
python 3.9 bookworm in docker
