### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 28

### ISSUE THREAD

**Issue by qiailin** [celery/django-celery-beat#24]
celery==4.0.0
Django==1.10.3
django-celery-beat==1.0.1
django-celery-results==1.0.1

===========================================
# CELERY TASK
CELERY_BROKER_URL = 'redis://:xx@127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://:taiyi@127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

 "celery -A app worker --loglevel=INFO -P gevent"

 -------------- celery@PC0018 v4.0.2 (latentcall)
---- **** -----
--- * ***  * -- Windows-8-6.2.9200 2017-02-13 11:39:14
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         richtrading-system.trading:0x3e0e0f0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://:**@xxxx/0
- *** --- * --- .> concurrency: 4 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

[tasks]

the transport is error and report :

[2017-02-13 11:31:43,868: WARNING/MainProcess] Traceback (most recent call last):
[2017-02-13 11:31:43,869: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 859, in emit
[2017-02-13 11:31:43,875: WARNING/MainProcess] msg = self.format(record)
[2017-02-13 11:31:43,875: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 732, in format
[2017-02-13 11:31:43,878: WARNING/MainProcess] return fmt.format(record)
[2017-02-13 11:31:43,878: WARNING/MainProcess] File "c:\python27\lib\site-packages\celery\utils\log.py", line 153, in format
[2017-02-13 11:31:43,881: WARNING/MainProcess] msg = logging.Formatter.format(self, record)
[2017-02-13 11:31:43,885: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 471, in format
[2017-02-13 11:31:43,892: WARNING/MainProcess] record.message = record.getMessage()
[2017-02-13 11:31:43,894: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 335, in getMessage
[2017-02-13 11:31:43,894: WARNING/MainProcess] msg = msg % self.args
[2017-02-13 11:31:43,897: WARNING/MainProcess] UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 28: invalid continuation byte
[2017-02-13 11:31:43,898: WARNING/MainProcess] Logged from file consumer.py, line 425
[2017-02-13 11:31:46,917: WARNING/MainProcess] Traceback (most recent call last):
[2017-02-13 11:31:46,918: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 859, in emit
[2017-02-13 11:31:46,921: WARNING/MainProcess] msg = self.format(record)
[2017-02-13 11:31:46,921: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 732, in format
[2017-02-13 11:31:46,924: WARNING/MainProcess] return fmt.format(record)
[2017-02-13 11:31:46,924: WARNING/MainProcess] File "c:\python27\lib\site-packages\celery\utils\log.py", line 153, in format
[2017-02-13 11:31:46,927: WARNING/MainProcess] msg = logging.Formatter.format(self, record)
[2017-02-13 11:31:46,927: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 471, in format
[2017-02-13 11:31:46,928: WARNING/MainProcess] record.message = record.getMessage()
[2017-02-13 11:31:46,930: WARNING/MainProcess] File "c:\python27\lib\logging\__init__.py", line 335, in getMessage
[2017-02-13 11:31:46,931: WARNING/MainProcess] msg = msg % self.args
[2017-02-13 11:31:46,933: WARNING/MainProcess] UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 28: invalid continuation byte
[2017-02-13 11:31:46,934: WARNING/MainProcess] Logged from file consumer.py, line 425

**Comment by Gentyk** [comment]
Why did you close this bug? If he has a solution, then please provide a link.

**Comment by Gentyk** [comment]
I saw some solutions of this error but they don't  satisfy my requirements. So please give your solution of this error.
