### ISSUE TITLE
OperationalError at /admin/django_celery_beat/intervalschedule/add/

### ISSUE THREAD

**Issue by Kazatel** [celery/django-celery-beat#247]
when I try to write into DB, I got this error.

Request Method: | POST
-- | --
http://<server>/admin/django_celery_beat/intervalschedule/add/
1.11.3
OperationalError
(1785, 'Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.')
/opt/app/data/tm480h/project/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py  in defaulterrorhandler, line 36
/opt/app/data/tm480h/project/bin/python

All worked fine on my test DB, where we don't have replication setup on database.

One of the suggestion I fount to fix that is , to disable GTID on mysql database, however I need to discuss this with DB team and if company policy allow us to do that.

I would like to know if by any change I can change celery beat source code to do comits imidiately to transanctional table or if I can use any other workeround.

**Comment by liquidpele** [comment]
What table types did django create?  It looks like it maybe is mixing innodb and myism tables or something?

**Comment by Kazatel** [comment]
dev
mysql> mysql> SHOW TABLE STATUS WHERE `Name` LIKE "%django%";
+-------------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-------------------+----------+----------------+---------+
| Name                                | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time          | Collation         | Checksum | Create_options | Comment |
+-------------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-------------------+----------+----------------+---------+
| django_admin_log                    | MyISAM |      10 | Dynamic    |  381 |             59 |       22716 | 281474976710655 |        18432 |         0 |            390 | 2019-04-15 03:21:04 | 2019-05-02 08:50:27 | 2019-04-15 03:21:04 | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_crontabschedule  | InnoDB |      10 | Dynamic    |    2 |           8192 |       16384 |               0 |            0 |         0 |              3 | 2019-05-02 05:04:02 | 2019-05-02 08:28:27 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_intervalschedule | InnoDB |      10 | Dynamic    |    2 |           8192 |       16384 |               0 |            0 |         0 |              3 | 2019-05-02 05:04:01 | 2019-05-02 08:50:08 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_periodictask     | InnoDB |      10 | Dynamic    |    5 |           3276 |       16384 |               0 |        65536 |         0 |              6 | 2019-05-02 05:04:02 | 2019-05-02 08:50:41 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_periodictasks    | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |           NULL | 2019-05-02 05:04:02 | 2019-05-02 08:50:41 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_solarschedule    | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |              1 | 2019-05-02 05:04:02 | NULL                | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_content_type                 | MyISAM |      10 | Dynamic    |  139 |             33 |        4636 | 281474976710655 |         9216 |         0 |            141 | 2019-04-15 03:21:04 | 2019-05-02 05:40:31 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_migrations                   | MyISAM |      10 | Dynamic    |  160 |             49 |        7944 | 281474976710655 |         5120 |         0 |            166 | 2019-04-15 03:21:04 | 2019-05-02 05:45:22 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_session                      | MyISAM |      10 | Dynamic    | 2737 |            273 |      748468 | 281474976710655 |       189440 |       108 |           NULL | 2019-04-15 03:21:04 | 2019-05-02 11:30:22 | 2019-04-15 03:21:04 | latin1_swedish_ci |     NULL |                |         |
+-------------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-------------------+----------+----------------+---------+
9 rows in set (0.01 sec)


prod
mysql> SHOW TABLE STATUS WHERE `Name` LIKE "%django%";
+-------------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-------------------+----------+----------------+---------+
| Name                                | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time          | Collation         | Checksum | Create_options | Comment |
+-------------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-------------------+----------+----------------+---------+
| django_admin_log                    | MyISAM |      10 | Dynamic    |  467 |             60 |       28104 | 281474976710655 |        23552 |         0 |            468 | 2018-01-25 02:08:51 | 2019-05-03 10:00:24 | 2018-01-25 02:08:52 | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_crontabschedule  | InnoDB |      10 | Dynamic    |    2 |           8192 |       16384 |               0 |            0 |         0 |              4 | 2019-05-02 16:27:38 | 2019-05-02 19:16:41 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_intervalschedule | InnoDB |      10 | Dynamic    |    2 |           8192 |       16384 |               0 |            0 |         0 |              6 | 2019-05-02 16:27:34 | NULL                | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_periodictask     | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        65536 |         0 |              2 | 2019-05-02 16:27:39 | 2019-05-03 04:02:50 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_periodictasks    | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |           NULL | 2019-05-02 16:27:35 | 2019-05-02 19:16:41 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_celery_beat_solarschedule    | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |              1 | 2019-05-02 16:27:37 | NULL                | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_content_type                 | MyISAM |      10 | Dynamic    |  136 |             33 |        4540 | 281474976710655 |         9216 |         0 |            138 | 2018-01-25 02:08:52 | 2019-05-02 16:27:47 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_migrations                   | MyISAM |      10 | Dynamic    |  105 |             49 |        5160 | 281474976710655 |         4096 |         0 |            110 | 2018-01-25 02:08:52 | 2019-05-02 16:27:40 | NULL                | latin1_swedish_ci |     NULL |                |         |
| django_session                      | MyISAM |      10 | Dynamic    | 3837 |            279 |     1074100 | 281474976710655 |       281600 |         0 |           NULL | 2018-01-25 02:08:52 | 2019-05-03 13:37:23 | 2018-01-25 02:08:52 | latin1_swedish_ci |     NULL |                |         |
+-------------------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+-------------------+----------+----------------+---------+
9 rows in set (0.00 sec)

mysql>

**Comment by Kazatel** [comment]
I let log raw sql, here is the output
`
(0.044) INSERT INTO `django_celery_beat_intervalschedule` (`every`, `period`) VALUES (30, 'seconds'); args=[30, u'seconds']
(0.044) SELECT `django_celery_beat_periodictasks`.`ident`, `django_celery_beat_periodictasks`.`last_update` FROM `django_celery_beat_periodictasks` WHERE `django_celery_beat_periodictasks`.`ident` = 1; args=(1,)
(0.044) UPDATE `django_celery_beat_periodictasks` SET `last_update` = '2019-05-03 11:03:54' WHERE `django_celery_beat_periodictasks`.`ident` = 1; args=(u'2019-05-03 11:03:54', 1)
(0.044) INSERT INTO `django_admin_log` (`action_time`, `user_id`, `content_type_id`, `object_id`, `object_repr`, `action_flag`, `change_message`) VALUES ('2019-05-03 11:03:54', 63, 133, '5', 'every 30 seconds', 1, '[{\"added\": {}}]'); args=[u'2019-05-03 11:03:54', 63, 133, u'5', u'every 30 seconds', 1, '[{"added": {}}]']
Internal Server Error: /admin/django_celery_beat/intervalschedule/add/
Traceback (most recent call last):
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/contrib/admin/options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/contrib/admin/options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/contrib/admin/options.py", line 1452, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/contrib/admin/options.py", line 726, in log_addition
    change_message=message,
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/contrib/admin/models.py", line 32, in log_action
    change_message=change_message,
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/models/sql/compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/Django-1.11.3-py2.7.egg/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/opt/app/data/tm480h/project/lib/python2.7/site-packages/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1785, 'Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.')
`

**Comment by liquidpele** [comment]
yup, you have a mix of MyISAM and innodb tables.

**Comment by liquidpele** [comment]
No idea why django used MyISAM tables, but they were created much earlier (2018-01-25 02:08:52), probably when your setup was different or something.  I'd recommend only using innodb tables.  

> Django expects the database to support Unicode (UTF-8 encoding) and delegates to it the task of enforcing transactions and referential integrity. It is important to be aware of the fact that the two latter ones aren’t actually enforced by MySQL when using the MyISAM storage engine, see the next section.

https://docs.djangoproject.com/en/2.2/ref/databases/#version-support

**Comment by Kazatel** [comment]
Our project is running for some time and looks like we have created our first tables with older MYSQL version , then we upgraded to never version. 
For better understanding:
The InnoDB storage engine is the default storage engine when creating tables starting with release 5.7 of MySQL.
The MyISAM storage engine is obsolete with release 5.7. you have to explicitly request it on your create table statement.

TO FIX problem I have to change engine.

`ALTER TABLE django_admin_log ENGINE=InnoDB;`

All started to work after the engine has been changed. 
Thank you very much for your help and support and thanks a lot for great module.
Wish you all the best for future.
Regards Tomas
