### ISSUE TITLE
Django timezone and DST issue

### ISSUE THREAD

**Issue by jdavisp3** [celery/django-celery-beat#285]
### Summary: Exception when a timezone is configured for Django and `last_run_at` is ambiguous.

Include a *brief* description of the problem here, and fill out the version info below.  

* Celery Version: 4.3.0
* Celery-Beat Version: 1.5.0 

### Exact steps to reproduce the issue:
1. Have a timezone configured for Django and have a periodic task run during the hour before a daylight savings time change so `last_run_at` is during that time.
2. After the change `django-celery-beat` will fail with a traceback [here](https://github.com/celery/django-celery-beat/blob/953df59dd634c846879243cfe673423ede254e6a/django_celery_beat/schedulers.py#L137).

### Detailed information

`pytz.exceptions.AmbiguousTimeError: 2019-11-03 01:00:00.336812`

**Comment by auvipy** [comment]
can you try celery 4.4.0rc3 and this libray from master and report back again?

**Comment by bk-equityzen** [comment]
I also got this error. The full traceback is: 
```
AmbiguousTimeError: 2019-11-03 01:00:00.010677
  File "usr/local/bin/celery", line 10, in <module>
    sys.exit(main())
  File "celery/__main__.py", line 16, in main
    _main()
  File "celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "celery/bin/beat.py", line 109, in run
    return beat().run()
  File "celery/apps/beat.py", line 81, in run
    self.start_scheduler()
  File "celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "celery/beat.py", line 597, in start
    interval = self.scheduler.tick()
  File "celery/beat.py", line 298, in tick
    self.populate_heap()
  File "celery/beat.py", line 272, in populate_heap
    is_due, next_call_delay = entry.is_due()
  File "django_celery_beat/schedulers.py", line 134, in is_due
    return self.schedule.is_due(make_aware(self.last_run_at))
  File "django_celery_beat/utils.py", line 27, in make_aware
    value = timezone.make_aware(value, timezone.get_default_timezone())
  File "django/utils/timezone.py", line 285, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "pytz/tzinfo.py", line 349, in localize
    raise AmbiguousTimeError(dt)
```

I suspect that celery beat should be doing something similar to celery's version of `make_aware` to catch `AmbiguousTimeError`

**Comment by jdavisp3** [comment]
cc @hrichards

**Comment by bk-equityzen** [comment]
Is this possibly fixed by https://github.com/celery/django-celery-beat/pull/294/files ?

**Comment by hrichards** [comment]
Sorry for the silence on this issue, y'all, especially leading to automatic closure.

@jdavisp3 and I recently bumped our version of DCB from 1.5.0 to 1.6.0, and I can confirm that such an upgrade *did* fix the timezone issue reported in this ticket, so it is closed justifiably.  I'm mentioning this here for posterity.

Below is some copypasta from us explicitly demonstrating the error and that the upgrade fixed it.

Love the library, y'all.  Thanks a lot for your hard work, @auvipy et al.

### Recreate ambiguous datetime error

1.  I'll be using my usual once-a-minute "heartbeat" task for testing:
    ```diff
    diff --git a/tasks.py b/tasks.py
    index d46094e2a0e..438a91af5c4 100644
    --- a/tasks.py
    +++ b/tasks.py
    @@ -217,3 +217,8 @@ def record_celery_queue_metrics():
                 len(task_lock),
                 tags=["celery_once", "lock:{}".format(task_lock_basename)],
             )
    +
    +
    +@periodic_task(run_every=timedelta(minutes=1))
    +def heartbeat():
    +    logger.info("Can't you heeeeeear... the poundin' of my heartbeat?!")
    ```
2. On `master` in `make shell`, run the following:
    
    First, create and demonstrate an ambiguous datetime using the same code DCB uses:
    
    ```
    In [28]: ambiguous_datetime = datetime.datetime(2021, 11, 7, 1, 30)                                                                                                                                                                                                             
    
    In [29]: timezone.make_aware(ambiguous_datetime, timezone.get_current_timezone())                                                                                                                                                                                               
    ---------------------------------------------------------------------------
    AmbiguousTimeError                        Traceback (most recent call last)
    <ipython-input-29-fde386d832c6> in <module>
    ----> 1 timezone.make_aware(ambiguous_datetime, timezone.get_current_timezone())
    
    ~/website/vendor/venv/lib/python3.6/site-packages/django/utils/timezone.py in make_aware(value, timezone, is_dst)
        283     if hasattr(timezone, 'localize'):
        284         # This method is available for pytz time zones.
    --> 285         return timezone.localize(value, is_dst=is_dst)
        286     else:
        287         # Check that we won't overwrite the timezone of an aware datetime.
    
    ~/website/vendor/venv/lib/python3.6/site-packages/pytz/tzinfo.py in localize(self, dt, is_dst)
        347         # ambiguous case
        348         if is_dst is None:
    --> 349             raise AmbiguousTimeError(dt)
        350 
        351         # Filter out the possiblilities that don't match the requested
    
    AmbiguousTimeError: 2021-11-07 01:30:00
    ```
3. Then assign that value to the heartbeat DCB PeriodicTask:
    ```
    In [4]:     
   ...:     PeriodicTask.objects.filter(name="tasks.heartbeat").update(last_run_at=ambiguous_datetime) 
   ...:     PeriodicTasks.update_changed() 
   ...:     heartbeat = PeriodicTask.objects.get(name="tasks.heartbeat") 
   ...:     print(heartbeat.last_run_at)                                                                                                                                                                                                                                        
    2021-11-07 01:30:00
    ```
4. Restart Celery with `make down up`.
5. Look in the Beat logs for a recreation of the error:
    ```
    [2021-11-09 11:02:40,255] {"title": "beat: Ticking with max interval->5.00 seconds", "utc_time": "2021-11-09T19:02:40.256936", "logname": "celery.beat"}
    [2021-11-09 11:02:40,300: INFO/MainProcess] Writing entries...
    [2021-11-09 11:02:40,300] {"title": "beat raised exception <class 'pytz.exceptions.AmbiguousTimeError'>: AmbiguousTimeError(datetime.datetime(2021, 11, 7, 1, 30),)", "utc_time": "2021-11-09T19:02:40.300920", "logname": "celery.beat", "traceback": [...], line 285, in make_aware\n    return timezone.localize(value, is_dst=is_dst)\n  File \"/home/docker/website/vendor/venv/lib/python3.6/site-packages/pytz/tzinfo.py\", line 349, in localize\n    raise AmbiguousTimeError(dt)\npytz.exceptions.AmbiguousTimeError: 2021-11-07 01:30:00\n"}
    [2021-11-09 11:02:40,306: INFO/MainProcess] Writing entries...
    [2021-11-09 11:02:40,306: INFO/MainProcess] Writing entries...
    ```
6.  `make down` and switch to this branch.
7. Run `make up`.  Upon running Beat with the new DCB version, the Beat startup error is corrected:
    ```
    [2021-11-09 11:07:19,830] {"title": "Task accepted: tasks.heartbeat[ba36efd3-4674-46d3-bf46-5fe1fbde3252] pid:262", "utc_time": "2021-11-09T19:07:19.830755", "logname": "celery.worker.request"}
    [2021-11-09 11:07:19,830] {"title": "Can't you heeeeeear... the poundin' of my heartbeat?!", "utc_time": "2021-11-09T19:07:19.830762", "logname": "tasks"}
    ```
