### ISSUE TITLE
Migrations fail with django.db.utils.OperationalError: (3775, 'Statement violates GTID consistency)

### ISSUE THREAD

**Issue by AlaaElrifaie** [celery/django-celery-beat#369]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 5.0.0
* Celery-Beat Version: 2.0.0

### Exact steps to reproduce the issue:
1. Installed Celery:
`pipenv install Celery`
2. Installed celery[redis]
`pipenv install "celery[redis]"`
3. Installed django-celery-beat
`pipenv install django-celery-beat`
4. Added 'django_celery_beat' to INSTALLED_APPS module.
5. Applied migrations:
`python manage.py migrate`

### Detailed information

Database migration fails giving me the following output:
```
Running migrations:
  Applying django_celery_beat.0009_periodictask_headers...Traceback (most recent call last):
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (3775, 'Statement violates GTID consistency: ALTER TABLE ... ADD COLUMN .. with expression as DEFAULT.')    

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv     
    self.execute(*args, **cmd_options)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\core\management\base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\core\management\commands\migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration      
    state = migration.apply(state, schema_editor)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\migrations\operations\fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\mysql\schema.py", line 89, in add_field
    super().add_field(model, field)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\base\schema.py", line 487, in add_field
    self.execute(sql, params)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\base\schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers     
    return executor(sql, params, many, context)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    return self.cursor.execute(sql, params)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\Alaa\.virtualenvs\Subordinate-Functions-ENV\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (3775, 'Statement violates GTID consistency: ALTER TABLE ... ADD COLUMN .. with expression as DEFAULT.') 
```
I know that Celery doesn't support Windows, I am aware of that so I am using Ubuntu for development, but tested the migration using Windows to be able to copy the output (I couldn't on my Ubuntu machine).

Thanks in advance.

**Comment by auvipy** [comment]
did you try the newest release?

**Comment by auvipy** [comment]
can you check this? https://stackoverflow.com/questions/40724046/mysql-gtid-consistency-violation or django-celery-beat is causing this?
