### ISSUE TITLE
Starting celery beat service throws an error (ModuleNotFoundError: No module named 'celery.utils.encoding')

### ISSUE THREAD

**Issue by AlaaElrifaie** [celery/django-celery-beat#370]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 5.0.0
* django-celery-beat Version: 2.0.0

### Exact steps to reproduce the issue:
1. Running the following:
`celery -A gaia beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler`

### Detailed information

I am getting the following output:
```
celery beat v5.0.0 (singularity) is starting.
Traceback (most recent call last):
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/bin/celery.py", line 150, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/bin/beat.py", line 70, in beat
    return beat().run()
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/apps/beat.py", line 77, in run
    self.start_scheduler()
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/apps/beat.py", line 96, in start_scheduler
    print(self.banner(service))
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/apps/beat.py", line 118, in banner
    c.reset(self.startup_info(service))),
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/apps/beat.py", line 128, in startup_info
    scheduler = service.get_scheduler(lazy=True)
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/celery/beat.py", line 653, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alaa/.local/share/virtualenvs/GAIA-Backend-c1qbxYN4/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 11, in <module>
    from celery.utils.encoding import safe_str, safe_repr
ModuleNotFoundError: No module named 'celery.utils.encoding'
```

Noting that running `celery -A gaia beat -l INFO` works with no issues.

**Comment by LaurentTreguier** [comment]
Looks like #364; there is a quick monkey-patch [down in the comments](https://github.com/celery/django-celery-beat/issues/364#issuecomment-704380827) to get around this issue for the time being

**Comment by thedrow** [comment]
Yes this indeed is a duplicate.
I'm well aware that this is a problem. I've got other priorities at the moment but I'm on it.
