### ISSUE TITLE
Django celery beat scheduler failing to start

### ISSUE THREAD

**Issue by EricOuma** [celery/django-celery-beat#404]
### Summary:

I have been following a tutorial on how to use celery with Django. I however keep on getting this error that I have no clue about. I don't understand why celery beat is trying to use role 'eric' and I have clearly defined my database settings

* Celery Version: 4.4.7
* Django-Celery-Beat Version: 2.2.0
* Flower version: 0.9.7
* Django version: 3.1.6

### Exact steps to reproduce the issue:
1. celery -A kncci worker -l info
2. flower -A kncci --port=5555
3. celery -A kncci beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

### Here is the traceback containing the error I am getting
        `celery beat v4.4.7 (cliffs) is starting.
        __    -    ... __   -        _
        LocalTime -> 2021-04-28 14:47:07
        Configuration ->
            . broker -> amqp://guest:**@localhost:5672//
            . loader -> celery.loaders.app.AppLoader
            . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
        
            . logfile -> [stderr]@%INFO
            . maxinterval -> 5.00 seconds (5s)
        [2021-04-28 14:47:07,437: INFO/MainProcess] beat: Starting...
        [2021-04-28 14:47:07,439: CRITICAL/MainProcess] beat raised exception <class 'django.db.utils.OperationalError'>: OperationalError('FATAL:  role "eric" does not exist\n')
        Traceback (most recent call last):
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/kombu/utils/objects.py", line 42, in __get__
            return obj.__dict__[self.__name__]
        KeyError: 'scheduler'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
            self.connect()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
            self.connection = self.get_new_connection(conn_params)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
            connection = Database.connect(**conn_params)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
            conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
        psycopg2.OperationalError: FATAL:  role "eric" does not exist
        
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/celery/apps/beat.py", line 109, in start_scheduler
            service.start()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/celery/beat.py", line 622, in start
            humanize_seconds(self.scheduler.max_interval))
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/kombu/utils/objects.py", line 44, in __get__
            value = obj.__dict__[self.__name__] = self.__get(obj)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/celery/beat.py", line 666, in scheduler
            return self.get_scheduler()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/celery/beat.py", line 657, in get_scheduler
            return symbol_by_name(self.scheduler_cls, aliases=aliases)(
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 231, in __init__
            Scheduler.__init__(self, *args, **kwargs)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/celery/beat.py", line 257, in __init__
            self.setup_schedule()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 239, in setup_schedule
            self.install_default_entries(self.schedule)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 361, in schedule
            self._schedule = self.all_as_schedule()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 245, in all_as_schedule
            for model in self.Model.objects.enabled():
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
            self._fetch_all()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
            self._result_cache = list(self._iterable_class(self))
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
            results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
            cursor = self.connection.cursor()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
            return self._cursor()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
            self.ensure_connection()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
            self.connect()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
            raise dj_exc_value.with_traceback(traceback) from exc_value
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
            self.connect()
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
            self.connection = self.get_new_connection(conn_params)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
            connection = Database.connect(**conn_params)
          File "/home/eric/Documents/kncci_api/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
            conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
        django.db.utils.OperationalError: FATAL:  role "eric" does not exist`

**Comment by auvipy** [comment]
this is your database issue in django. not related to lib.
