### ISSUE TITLE
Couldn't apply scheduled task (required positional argument)

### ISSUE THREAD

**Issue by aprilahijriyan** [celery/django-celery-beat#415]
### Summary:

The task created by `@shared_task` cannot be executed because it requires arguments.

* Celery Version: 5.1.0 (sun-harmonics)
* Celery-Beat Version: 2.2.0

### Exact steps to reproduce the issue:

1. Create a task with `@shared_task` (which has arguments)
2. Add `ClockedSchedule`
3.  Add `args` with id value (`json.dumps([self.id])`)

* This is the task I use.

```python
@shared_task(name="schedule_post")
def schedule_post(id):
    print("post id:", id)
    post = Post.objects.get(pk=id)
    post.status = Status.PUBLISH
    post.save()
    print("Post published:", post.slug)
```

### Detailed information

```
TypeError: schedule_post() missing 1 required positional argument: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/titiw/.local/share/virtualenvs/kntlpepek_2-9laxC7T5/lib/python3.8/site-packages/celery/beat.py", line 287, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File "/Users/titiw/.local/share/virtualenvs/kntlpepek_2-9laxC7T5/lib/python3.8/site-packages/celery/beat.py", line 412, in apply_async
    reraise(SchedulingError, SchedulingError(
  File "/Users/titiw/.local/share/virtualenvs/kntlpepek_2-9laxC7T5/lib/python3.8/site-packages/celery/exceptions.py", line 108, in reraise
    raise value.with_traceback(tb)
  File "/Users/titiw/.local/share/virtualenvs/kntlpepek_2-9laxC7T5/lib/python3.8/site-packages/celery/beat.py", line 404, in apply_async
    return task.apply_async(entry_args, entry_kwargs,
  File "/Users/titiw/.local/share/virtualenvs/kntlpepek_2-9laxC7T5/lib/python3.8/site-packages/celery/app/task.py", line 537, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
celery.beat.SchedulingError: Couldn't apply scheduled task schedule_post: schedule_post() missing 1 required positional argument: 'id'
```

* The command I use to run celery `worker` and `beat`:

```
celery -A app worker -l debug --beat
``` 

* My config:

```python
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6380"
CELERY_BROKER_URL = CELERY_RESULT_BACKEND
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TIMEZONE = "Asia/Jakarta"
CELERY_ENABLE_UTC = False
```

**Comment by auvipy** [comment]
you are not providing the argument

**Comment by aprilahijriyan** [comment]
@auvipy sorry for the slow response, unfortunately I no longer use ``celery``. as i remember i passed an argument to the task function.
