### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by pjaol** [celery/django-celery-beat#419]
### Summary:

$ pip freeze |grep -E -i "celery|django"
celery==5.1.0
celery-redbeat==2.0.0
Django==3.2.4
django-celery-beat==2.2.0
django-timezone-field==4.1.2

python -V
Python 3.8.9

### Exact steps to reproduce the issue:
1. updated settings.py adding to settings.py
```INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat'
]
```
2. python manage.py runserver  ->  works fine
3. run  $ celery beat -S django   ->  fails

### Detailed information
```sh
 $ celery beat -S django
celery beat v5.1.0 (sun-harmonics) is starting.
Traceback (most recent call last):
  File "/xxxx/.env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/xxxx/.env/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/xxxx/.env/lib/python3.8/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/xxxx/.env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/xxxx/.env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/xxxx/.env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxxx/.env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/xxxx/.env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/xxxx/.env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/xxxx/.env/lib/python3.8/site-packages/celery/bin/base.py", line 132, in caller
    return f(ctx, *args, **kwargs)
  File "/xxxx/.env/lib/python3.8/site-packages/celery/bin/beat.py", line 72, in beat
    return beat().run()
  File "/xxxx/.env/lib/python3.8/site-packages/celery/apps/beat.py", line 77, in run
    self.start_scheduler()
  File "/xxxx/.env/lib/python3.8/site-packages/celery/apps/beat.py", line 96, in start_scheduler
    print(self.banner(service))
  File "/xxxx/.env/lib/python3.8/site-packages/celery/apps/beat.py", line 118, in banner
    c.reset(self.startup_info(service))),
  File "/xxxx/.env/lib/python3.8/site-packages/celery/apps/beat.py", line 128, in startup_info
    scheduler = service.get_scheduler(lazy=True)
  File "/xxxx/.env/lib/python3.8/site-packages/celery/beat.py", line 671, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/xxxx/.env/lib/python3.8/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/xxxx/.env/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 22, in <module>
    from .models import (
  File "/xxxx/.env/lib/python3.8/site-packages/django_celery_beat/models.py", line 75, in <module>
    class SolarSchedule(models.Model):
  File "/xxxx/.env/lib/python3.8/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/xxxx/.env/lib/python3.8/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "/xxxx/.env/lib/python3.8/site-packages/django/apps/registry.py", line 136, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Have tried adding django.setup() to __init__.py
```python
import django;
import pymysql
pymysql.install_as_MySQLdb()
django.setup()
```

Gets a little further 
```
ImportError: cannot import name 'PeriodicTask' from partially initialized module 'django_celery_beat.models' (most likely due to a circular import) (/xxxx/.env/lib/python3.8/site-packages/django_celery_beat/models.py)
```

no additional project / app just running celery beat

**Comment by pjaol** [comment]
False alarm - required a project and celery to be loaded as documented in celery.py and __init__.py
https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html
and for celery beat to be called with -A <project name>
