### ISSUE TITLE
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.

### ISSUE THREAD

**Issue by 68110923** [celery/django-celery-beat#428]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  
* django:2.2.24
* Celery Version: 5.1.2
* Celery-Beat Version: 2.2.1

### Exact steps to reproduce the issue:
1. django settings.py TIME_ZONE = 'Asia/Shanghai'  USE_TZ = False
2. celery timezone = 'Asia/Shanghai' enable_utc = False  beat_tz_aware = False
3. django和celery配置如上，celery beat出现BUG
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.

### Detailed information

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/apps/beat.py", line 105, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 651, in start
    self.scheduler._do_sync()
  File "/usr/local/lib/python3.8/site-packages/celery/beat.py", line 430, in _do_sync
    self.sync()
  File "/usr/local/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 301, in sync
    self.schedule[name].save()
  File "/usr/local/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 164, in save
    obj.save()
  File "/usr/local/lib/python3.8/site-packages/django_celery_beat/models.py", line 581, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/compiler.py", line 44, in as_sql
    update_query, update_params = super().as_sql()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1525, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1428, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 253, in adapt_datetimefield_value
    raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.

**Comment by auvipy** [comment]
this is might be a mysql backend issue

**Comment by 68110923** [comment]
def adapt_datetimefield_value(self, value):
        if value is None:
            return None

        # Expression values are adapted by the database.
        if hasattr(value, 'resolve_expression'):
            return value

        # MySQL doesn't support tz-aware datetimes
        if timezone.is_aware(value):
            if settings.USE_TZ:
                value = timezone.make_naive(value, self.connection.timezone)
            else:
                raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
        return str(value)
上面部分是django2.2.24的源码，mysql不支持aware

关闭了时区功能，却向MySQL中存储了一个aware datetime object，就会得到以下报错：
"ValueError: MySQL backend does not support timezone-aware datetimes. "
但是我找不到django-celery-beat在定时任务启动的时候的代码

**Comment by 68110923** [comment]
启动后第一次djngo的adapt_datetimefield_value方法接收到了正确的（预期的）时间格式
正常跑了三分钟后adapt_datetimefield_value方法又接收到了2021-08-24 16:51:44.152491+08:00格式的时间
然后adapt_datetimefield_value方法抛出了错

问题应该出在django_celery_beat.schedulers.py.sync的self.schedule[name].save()
但是我找了好久仍然找不到 我放弃了 我就直接改一下自己能用算了
\site-packages\django\db\backends\mysql\operations.py   DatabaseOperations.adapt_datetimefield_value 修改为
    def adapt_datetimefield_value(self, value):
        if value is None:
            return None

        # Expression values are adapted by the database.
        if hasattr(value, 'resolve_expression'):
            return value

        # MySQL doesn't support tz-aware datetimes
        if timezone.is_aware(value):
            if settings.USE_TZ:
                value = timezone.make_naive(value, self.connection.timezone)
            elif re.search('\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+',str(value)).group(): # 临时添加
                value = parser.parse(str(value)).replace(tzinfo=None)    # 临时添加
            else:
                raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
        return str(value)


全部报错日志
D:\app\Python\python37\python.exe D:/app/Python/python37/Scripts/celery.exe -A suncent beat -l info
celery beat v5.1.2 (sun-harmonics) is starting.
[2021-08-24 16:48:43,738: INFO/MainProcess] beat: Starting...
[2021-08-24 16:48:43,739: WARNING/MainProcess] sync------set()
__    -    ... __   -        _
LocalTime -> 2021-08-24 16:48:43
Configuration ->
    . broker -> redis://:**@47.119.200.228:6379/6
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> django_celery_beat.schedulers.DatabaseScheduler

    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 seconds (5s)
[2021-08-24 16:48:43,824: WARNING/MainProcess] adapt_datetimefield_value----------------2021-08-24 16:48:43.819642
[2021-08-24 16:48:43,824: WARNING/MainProcess] 

[2021-08-24 16:48:43,847: WARNING/MainProcess] adapt_datetimefield_value----------------2021-08-24 16:48:43.842490
[2021-08-24 16:48:43,847: WARNING/MainProcess] 

[2021-08-24 16:48:43,854: WARNING/MainProcess] adapt_datetimefield_value----------------None
[2021-08-24 16:48:43,854: WARNING/MainProcess] 

[2021-08-24 16:48:43,854: WARNING/MainProcess] adapt_datetimefield_value----------------None
[2021-08-24 16:48:43,854: WARNING/MainProcess] 

[2021-08-24 16:48:43,854: WARNING/MainProcess] adapt_datetimefield_value----------------None
[2021-08-24 16:48:43,854: WARNING/MainProcess] 

[2021-08-24 16:48:43,854: WARNING/MainProcess] adapt_datetimefield_value----------------2021-08-24 16:48:43.854693
[2021-08-24 16:48:43,854: WARNING/MainProcess] 

[2021-08-24 16:48:46,801: WARNING/MainProcess] sync------set()
[2021-08-24 16:48:46,908: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:48:49,932: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:48:52,997: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:48:56,023: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:48:59,092: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:02,117: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:05,167: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:08,244: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:11,276: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:14,334: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:17,392: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:20,456: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:23,507: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:26,568: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:29,608: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:32,639: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:35,692: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:38,765: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:41,816: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:44,857: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:47,906: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:50,958: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:54,021: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:49:57,050: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:00,114: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:03,181: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:06,254: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:09,291: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:12,327: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:15,383: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:18,413: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:21,451: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:24,519: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:27,556: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:30,624: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:33,757: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:36,818: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:39,877: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:42,919: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:45,957: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:48,991: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:52,059: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:55,114: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:50:58,182: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:01,216: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:04,285: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:07,335: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:10,389: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:13,430: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:16,485: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:19,547: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:22,603: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:25,644: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:28,702: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:31,769: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:34,992: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:38,053: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:41,120: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:44,152: INFO/MainProcess] Scheduler: Sending due task 测试 (suncent.celery.test)
[2021-08-24 16:51:47,152: WARNING/MainProcess] sync------{'测试'}
[2021-08-24 16:51:47,152: WARNING/MainProcess] sync-----------测试
[2021-08-24 16:51:47,240: WARNING/MainProcess] adapt_datetimefield_value----------------None
[2021-08-24 16:51:47,240: WARNING/MainProcess] 

[2021-08-24 16:51:47,240: WARNING/MainProcess] adapt_datetimefield_value----------------None
[2021-08-24 16:51:47,240: WARNING/MainProcess] 

[2021-08-24 16:51:47,240: WARNING/MainProcess] adapt_datetimefield_value----------------2021-08-24 16:51:44.152491+08:00
[2021-08-24 16:51:47,240: WARNING/MainProcess] 

[2021-08-24 16:51:47,241: WARNING/MainProcess] adapt_datetimefield_value--------------D:\app\Python\python37\Lib\site-packages\django\db\backends\mysql\operations.py  200MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
[2021-08-24 16:51:47,241: WARNING/MainProcess] sync------set()
[2021-08-24 16:51:47,241: CRITICAL/MainProcess] beat raised exception <class 'ValueError'>: ValueError('MySQL backend does not support timezone-aware datetimes when USE_TZ is False.')
Traceback (most recent call last):
  File "D:\app\Python\python37\lib\site-packages\celery\apps\beat.py", line 105, in start_scheduler
    service.start()
  File "D:\app\Python\python37\lib\site-packages\celery\beat.py", line 651, in start
    self.scheduler._do_sync()
  File "D:\app\Python\python37\lib\site-packages\celery\beat.py", line 430, in _do_sync
    self.sync()
  File "D:\app\Python\python37\lib\site-packages\django_celery_beat\schedulers.py", line 303, in sync
    self.schedule[name].save()
  File "D:\app\Python\python37\lib\site-packages\django_celery_beat\schedulers.py", line 164, in save
    obj.save()
  File "D:\app\Python\python37\lib\site-packages\django_celery_beat\models.py", line 581, in save
    super().save(*args, **kwargs)
  File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 782, in save_base
    force_update, using, update_fields,
  File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 854, in _save_table
    forced_update)
  File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 903, in _do_update
    return filtered._update(values) > 0
  File "D:\app\Python\python37\lib\site-packages\django\db\models\query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "D:\app\Python\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1471, in execute_sql
    cursor = super().execute_sql(result_type)
  File "D:\app\Python\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1129, in execute_sql
    sql, params = self.as_sql()
  File "D:\app\Python\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1437, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "D:\app\Python\python37\lib\site-packages\django\db\models\fields\__init__.py", line 793, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "D:\app\Python\python37\lib\site-packages\django\db\models\fields\__init__.py", line 1436, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "D:\app\Python\python37\lib\site-packages\django\db\backends\mysql\operations.py", line 203, in adapt_datetimefield_value
    raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
[2021-08-24 16:51:47,243: WARNING/MainProcess] Traceback (most recent call last):

[2021-08-24 16:51:47,243: WARNING/MainProcess]   File "D:\app\Python\python37\lib\runpy.py", line 193, in _run_module_as_main

[2021-08-24 16:51:47,243: WARNING/MainProcess]     
[2021-08-24 16:51:47,243: WARNING/MainProcess] "__main__", mod_spec)
[2021-08-24 16:51:47,243: WARNING/MainProcess] 

[2021-08-24 16:51:47,243: WARNING/MainProcess]   File "D:\app\Python\python37\lib\runpy.py", line 85, in _run_code

[2021-08-24 16:51:47,245: WARNING/MainProcess]     
[2021-08-24 16:51:47,245: WARNING/MainProcess] exec(code, run_globals)
[2021-08-24 16:51:47,245: WARNING/MainProcess] 

[2021-08-24 16:51:47,245: WARNING/MainProcess]   File "D:\app\Python\python37\Scripts\celery.exe\__main__.py", line 7, in <module>

[2021-08-24 16:51:47,245: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\__main__.py", line 15, in main

[2021-08-24 16:51:47,245: WARNING/MainProcess]     
[2021-08-24 16:51:47,246: WARNING/MainProcess] sys.exit(_main())
[2021-08-24 16:51:47,246: WARNING/MainProcess] 

[2021-08-24 16:51:47,246: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\bin\celery.py", line 213, in main

[2021-08-24 16:51:47,246: WARNING/MainProcess]     
[2021-08-24 16:51:47,246: WARNING/MainProcess] return celery(auto_envvar_prefix="CELERY")
[2021-08-24 16:51:47,246: WARNING/MainProcess] 

[2021-08-24 16:51:47,246: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\click\core.py", line 829, in __call__

[2021-08-24 16:51:47,246: WARNING/MainProcess]     
[2021-08-24 16:51:47,246: WARNING/MainProcess] return self.main(*args, **kwargs)
[2021-08-24 16:51:47,246: WARNING/MainProcess] 

[2021-08-24 16:51:47,246: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\click\core.py", line 782, in main

[2021-08-24 16:51:47,246: WARNING/MainProcess]     
[2021-08-24 16:51:47,246: WARNING/MainProcess] rv = self.invoke(ctx)
[2021-08-24 16:51:47,247: WARNING/MainProcess] 

[2021-08-24 16:51:47,247: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\click\core.py", line 1259, in invoke

[2021-08-24 16:51:47,247: WARNING/MainProcess]     
[2021-08-24 16:51:47,247: WARNING/MainProcess] return _process_result(sub_ctx.command.invoke(sub_ctx))
[2021-08-24 16:51:47,247: WARNING/MainProcess] 

[2021-08-24 16:51:47,247: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\click\core.py", line 1066, in invoke

[2021-08-24 16:51:47,248: WARNING/MainProcess]     
[2021-08-24 16:51:47,248: WARNING/MainProcess] return ctx.invoke(self.callback, **ctx.params)
[2021-08-24 16:51:47,248: WARNING/MainProcess] 

[2021-08-24 16:51:47,248: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\click\core.py", line 610, in invoke

[2021-08-24 16:51:47,248: WARNING/MainProcess]     
[2021-08-24 16:51:47,248: WARNING/MainProcess] return callback(*args, **kwargs)
[2021-08-24 16:51:47,248: WARNING/MainProcess] 

[2021-08-24 16:51:47,248: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\click\decorators.py", line 21, in new_func

[2021-08-24 16:51:47,248: WARNING/MainProcess]     
[2021-08-24 16:51:47,248: WARNING/MainProcess] return f(get_current_context(), *args, **kwargs)
[2021-08-24 16:51:47,248: WARNING/MainProcess] 

[2021-08-24 16:51:47,248: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\bin\base.py", line 133, in caller

[2021-08-24 16:51:47,248: WARNING/MainProcess]     
[2021-08-24 16:51:47,248: WARNING/MainProcess] return f(ctx, *args, **kwargs)
[2021-08-24 16:51:47,248: WARNING/MainProcess] 

[2021-08-24 16:51:47,248: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\bin\beat.py", line 72, in beat

[2021-08-24 16:51:47,248: WARNING/MainProcess]     
[2021-08-24 16:51:47,248: WARNING/MainProcess] return beat().run()
[2021-08-24 16:51:47,248: WARNING/MainProcess] 

[2021-08-24 16:51:47,248: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\apps\beat.py", line 77, in run

[2021-08-24 16:51:47,248: WARNING/MainProcess]     
[2021-08-24 16:51:47,248: WARNING/MainProcess] self.start_scheduler()
[2021-08-24 16:51:47,248: WARNING/MainProcess] 

[2021-08-24 16:51:47,248: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\apps\beat.py", line 105, in start_scheduler

[2021-08-24 16:51:47,249: WARNING/MainProcess]     
[2021-08-24 16:51:47,249: WARNING/MainProcess] service.start()
[2021-08-24 16:51:47,260: WARNING/MainProcess] 

[2021-08-24 16:51:47,260: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\beat.py", line 651, in start

[2021-08-24 16:51:47,260: WARNING/MainProcess]     
[2021-08-24 16:51:47,260: WARNING/MainProcess] self.scheduler._do_sync()
[2021-08-24 16:51:47,260: WARNING/MainProcess] 

[2021-08-24 16:51:47,260: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\celery\beat.py", line 430, in _do_sync

[2021-08-24 16:51:47,260: WARNING/MainProcess]     
[2021-08-24 16:51:47,260: WARNING/MainProcess] self.sync()
[2021-08-24 16:51:47,260: WARNING/MainProcess] 

[2021-08-24 16:51:47,260: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django_celery_beat\schedulers.py", line 303, in sync

[2021-08-24 16:51:47,261: WARNING/MainProcess]     
[2021-08-24 16:51:47,261: WARNING/MainProcess] self.schedule[name].save()
[2021-08-24 16:51:47,261: WARNING/MainProcess] 

[2021-08-24 16:51:47,261: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django_celery_beat\schedulers.py", line 164, in save

[2021-08-24 16:51:47,261: WARNING/MainProcess]     
[2021-08-24 16:51:47,261: WARNING/MainProcess] obj.save()
[2021-08-24 16:51:47,261: WARNING/MainProcess] 

[2021-08-24 16:51:47,261: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django_celery_beat\models.py", line 581, in save

[2021-08-24 16:51:47,261: WARNING/MainProcess]     
[2021-08-24 16:51:47,261: WARNING/MainProcess] super().save(*args, **kwargs)
[2021-08-24 16:51:47,261: WARNING/MainProcess] 

[2021-08-24 16:51:47,261: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 744, in save

[2021-08-24 16:51:47,261: WARNING/MainProcess]     
[2021-08-24 16:51:47,262: WARNING/MainProcess] force_update=force_update, update_fields=update_fields)
[2021-08-24 16:51:47,262: WARNING/MainProcess] 

[2021-08-24 16:51:47,262: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 782, in save_base

[2021-08-24 16:51:47,262: WARNING/MainProcess]     
[2021-08-24 16:51:47,262: WARNING/MainProcess] force_update, using, update_fields,
[2021-08-24 16:51:47,262: WARNING/MainProcess] 

[2021-08-24 16:51:47,262: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 854, in _save_table

[2021-08-24 16:51:47,262: WARNING/MainProcess]     
[2021-08-24 16:51:47,262: WARNING/MainProcess] forced_update)
[2021-08-24 16:51:47,262: WARNING/MainProcess] 

[2021-08-24 16:51:47,262: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\base.py", line 903, in _do_update

[2021-08-24 16:51:47,262: WARNING/MainProcess]     
[2021-08-24 16:51:47,263: WARNING/MainProcess] return filtered._update(values) > 0
[2021-08-24 16:51:47,263: WARNING/MainProcess] 

[2021-08-24 16:51:47,263: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\query.py", line 760, in _update

[2021-08-24 16:51:47,263: WARNING/MainProcess]     
[2021-08-24 16:51:47,263: WARNING/MainProcess] return query.get_compiler(self.db).execute_sql(CURSOR)
[2021-08-24 16:51:47,263: WARNING/MainProcess] 

[2021-08-24 16:51:47,263: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1471, in execute_sql

[2021-08-24 16:51:47,263: WARNING/MainProcess]     
[2021-08-24 16:51:47,263: WARNING/MainProcess] cursor = super().execute_sql(result_type)
[2021-08-24 16:51:47,263: WARNING/MainProcess] 

[2021-08-24 16:51:47,263: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1129, in execute_sql

[2021-08-24 16:51:47,265: WARNING/MainProcess]     
[2021-08-24 16:51:47,265: WARNING/MainProcess] sql, params = self.as_sql()
[2021-08-24 16:51:47,265: WARNING/MainProcess] 

[2021-08-24 16:51:47,265: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1437, in as_sql

[2021-08-24 16:51:47,278: WARNING/MainProcess]     
[2021-08-24 16:51:47,278: WARNING/MainProcess] val = field.get_db_prep_save(val, connection=self.connection)
[2021-08-24 16:51:47,278: WARNING/MainProcess] 

[2021-08-24 16:51:47,278: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\fields\__init__.py", line 793, in get_db_prep_save

[2021-08-24 16:51:47,278: WARNING/MainProcess]     
[2021-08-24 16:51:47,278: WARNING/MainProcess] return self.get_db_prep_value(value, connection=connection, prepared=False)
[2021-08-24 16:51:47,278: WARNING/MainProcess] 

[2021-08-24 16:51:47,278: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\models\fields\__init__.py", line 1436, in get_db_prep_value

[2021-08-24 16:51:47,278: WARNING/MainProcess]     
[2021-08-24 16:51:47,279: WARNING/MainProcess] return connection.ops.adapt_datetimefield_value(value)
[2021-08-24 16:51:47,279: WARNING/MainProcess] 

[2021-08-24 16:51:47,279: WARNING/MainProcess]   File "D:\app\Python\python37\lib\site-packages\django\db\backends\mysql\operations.py", line 203, in adapt_datetimefield_value

[2021-08-24 16:51:47,279: WARNING/MainProcess]     
[2021-08-24 16:51:47,279: WARNING/MainProcess] raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
[2021-08-24 16:51:47,279: WARNING/MainProcess] 

[2021-08-24 16:51:47,279: WARNING/MainProcess] ValueError
[2021-08-24 16:51:47,279: WARNING/MainProcess] : 
[2021-08-24 16:51:47,279: WARNING/MainProcess] MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
[2021-08-24 16:51:47,279: WARNING/MainProcess] 

[2021-08-24 16:51:47,279: WARNING/MainProcess] sync------set()
[2021-08-24 16:51:47,279: WARNING/MainProcess] sync------set()

Process finished with exit code 1

**Comment by 68110923** [comment]
> 这可能是 mysql 后端问题

    def _default_now(self):
        # The PyTZ datetime must be localised for the Django-Celery-Beat
        # scheduler to work. Keep in mind that timezone arithmatic
        # with a localized timezone may be inaccurate.
        if getattr(settings, 'DJANGO_CELERY_BEAT_TZ_AWARE', True):
            now = self.app.now()
            now = now.tzinfo.localize(now.replace(tzinfo=None))
        else:
            # this ends up getting passed to maybe_make_aware, which expects
            # all naive datetime objects to be in utc time.
            now = datetime.datetime.utcnow()
        return now


在django的settings中配置  DJANGO_CELERY_BEAT_TZ_AWARE=False 即可
