### ISSUE TITLE
登录报错 pymysql.err.ProgrammingError: (1146, "Table 'celery.auth_user' doesn't exist")

### ISSUE THREAD

**Issue by solitary-sen** [celery/django-celery-beat#496]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 
* Celery-Beat Version: django-celery-beat-2.2.1

### Exact steps to reproduce the issue:
1. django.db.utils.ProgrammingError: (1146, "Table 'celery.auth_user' doesn't exist")
2. [05/Jan/2022 22:16:55] "POST /admin/login/?next=/admin/login HTTP/1.1" 500 292560
3. 

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.  

登录报错

Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\java\tools\python3.8\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\java\tools\python3.8\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "E:\java\tools\python3.8\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'celery.auth_user' doesn't exist")

**Comment by solitary-sen** [comment]
初始化应该使用python manage.py migrate

**Comment by auvipy** [comment]
really great
