### ISSUE TITLE
IntervalSchedule gives me django_celery_beat.models.DoesNotExist

### ISSUE THREAD

**Issue by mg64ve** [celery/django-celery-beat#499]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 5.2.3
* Celery-Beat Version: 2.2.1

### Exact steps to reproduce the issue:
1. Execute the attached script

### Detailed information

Just execute the following script:

```
import json
import django
django.setup()
from django.db import models
from django.utils import timezone
from django_enum_choices.fields import EnumChoiceField
from django_celery_beat.models import IntervalSchedule, PeriodicTask

IntervalSchedule.objects.get(every=1, period='minutes')
```

I am getting the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
django_celery_beat.models.DoesNotExist: IntervalSchedule matching query does not exist.
```

What is the issue?

**Comment by mg64ve** [comment]
The correct statement is:

`IntervalSchedule.objects.get(every=1, period=IntervalSchedule.MINUTES)`
