### ISSUE TITLE
ModuleNotFoundError: No module named 'django_celery_beatcorsheaders'

### ISSUE THREAD

**Issue by ajaiau0** [celery/django-celery-beat#500]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 5.2.3
* Celery-Beat Version:  2.2.1 
* django-celery-beat            2.2.1 

### Exact steps to reproduce the issue:
1. after installing django-celery-beat it show this error.
2. 
3. 

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.  

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/user/.cache/pypoetry/virtualenvs/yachtdrf-uHPalLI4-py3.8/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_celery_beatcorsheaders'

**Comment by auvipy** [comment]
you missed comma between two django apps 'django_celery_beatcorsheaders put comma after django_celery_beat and check corsheader. you should open stackoverflow Question.
