### ISSUE TITLE
django_celery_beat executes crontabscheduled task only once

### ISSUE THREAD

**Issue by poojashete** [celery/django-celery-beat#53]
I am trying to integrate django_celery_beat in project. When I setup task using django admin panel entries in database are reflected correctly and when I start project task gets executed successfully. Whereas on every successive attempt of sending task is rather failed or either message is not sent to broker.

My setup :

```
django_celery_beat : 1.0.1
celery: 4.0.1
```
Setting in celeryconfig:

```
CELERY_ENABLE_UTC = True
BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERYBEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
```
When I start celery I do get exception of :

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.4/dist-packages/celery/worker/pidbox.py", line 42, in on_message
   self.node.handle_message(body, message)
 File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 129, in handle_message
   return self.dispatch(**body)
 File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 112, in dispatch
   ticket=ticket)
 File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 135, in reply
   serializer=self.mailbox.serializer)
 File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 265, in _publish_reply
   **opts
 File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 181, in publish
   exchange_name, declare,
 File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 203, in _publish
   mandatory=mandatory, immediate=immediate,
 File "/usr/local/lib/python3.4/dist-packages/amqp/channel.py", line 1748, in _basic_publish
   (0, exchange, routing_key, mandatory, immediate), msg
 File "/usr/local/lib/python3.4/dist-packages/amqp/abstract_channel.py", line 64, in send_method
   conn.frame_writer(1, self.channel_id, sig, args, content)
 File "/usr/local/lib/python3.4/dist-packages/amqp/method_framing.py", line 174, in write_frame
   write(view[:offset])
 File "/usr/local/lib/python3.4/dist-packages/amqp/transport.py", line 269, in write
   self._write(s)
BrokenPipeError: [Errno 32] Broken pipe
```
Logs in beat.stderr.log:

```
[2017-06-12 05:40:00,002: INFO/MainProcess] Scheduler: Sending due task pooja_task (app.tasks.send_test_mail)
[2017-06-12 05:41:00,002: INFO/MainProcess] Scheduler: Sending due task pooja_task (app.tasks.send_test_mail)
[2017-06-12 05:42:00,002: INFO/MainProcess] Scheduler: Sending due task pooja_task (app.tasks.send_test_mail)
```
However from all above task sent, celery picks only first task and execute whenever I start by server. All other messages are avoided.

**Comment by wcsjtu** [comment]
I also encountered the same problem。 
celery: 4.1.0
django_celery_beat: 1.0.1

**Comment by auvipy** [comment]
with master?

**Comment by auvipy** [comment]
closing due to inactivity & hopefully fixed already
