### ISSUE TITLE
unicode characters in periodic task name raise exception

### ISSUE THREAD

**Issue by jerzyk** [celery/django-celery-beat#54]
```
[2017-06-20 11:49:47,155: CRITICAL/MainProcess] beat raised exception <type 'exceptions.UnicodeDecodeError'>: UnicodeDecodeError('ascii', 'Sprawd\xc5\xba logi', 6, 7, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/celery/apps/beat.py", line 107, in start_scheduler
    service.start()
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/celery/beat.py", line 528, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/celery/beat.py", line 572, in scheduler
    return self.get_scheduler()
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/celery/beat.py", line 567, in get_scheduler
    lazy=lazy,
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 179, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/celery/beat.py", line 204, in __init__
    self.setup_schedule()
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 187, in setup_schedule
    self.install_default_entries(self.schedule)
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 283, in schedule
    repr(entry) for entry in values(self._schedule)),
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 283, in <genexpr>
    repr(entry) for entry in values(self._schedule)),
  File "/.virtualenvs/im/local/lib/python2.7/site-packages/django_celery_beat/schedulers.py", line 162, in __repr__
    safe_repr(self.kwargs), self.schedule,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 6: ordinal not in range(128)
```

**Comment by mheppner** [comment]
Please provide your Python, Django, Celery, and django-celery-beat versions.

**Comment by jerzyk** [comment]
Python 2.7.12
Django==1.10.5
celery==4.0.2
django-celery-beat==1.0.1

**Comment by bparker98** [comment]
I ran into this same issue. It seems to be a problem with debug mode and repr for scheduled tasks with unicode in their names. I was able to work around it by subclassing the DatabaseScheduler class and overriding the logger statement in schedule()

**Comment by auvipy** [comment]
as this package dropped python2, are you still facing this? I will close if not

**Comment by jerzyk** [comment]
for python 3 this is no longer an issue, thanks.
