### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by mback2k** [celery/django-celery-beat#6]
Hello, I get the following error while opening the "Periodic tasks" changelist view with Django 1.8.16.
```
Internal Server Error: /admin/django_celery_beat/periodictask/
Traceback (most recent call last):
  File "/var/local/pyweb/virtualenv/dnsalloc/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/local/pyweb/virtualenv/dnsalloc/lib/python2.7/site-packages/django/contrib/admin/options.py", line 618, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/var/local/pyweb/virtualenv/dnsalloc/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/local/pyweb/virtualenv/dnsalloc/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/local/pyweb/virtualenv/dnsalloc/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/var/local/pyweb/virtualenv/dnsalloc/lib/python2.7/site-packages/django_celery_beat/admin.py", line 136, in changelist_view
    extra_context['wrong_scheduler'] = not is_database_scheduler(scheduler)
  File "/var/local/pyweb/virtualenv/dnsalloc/lib/python2.7/site-packages/django_celery_beat/utils.py", line 41, in is_database_scheduler
    return issubclass(symbol_by_name(scheduler), DatabaseScheduler)
TypeError: issubclass() arg 1 must be a class
```
Please take a look, thanks.

**Comment by mheppner** [comment]
Not sure if this is the correct answer, but if you followed the docs that say to use `-S django` on the command line, but don't say what to set for `CELERY_BEAT_SCHEDULER`, you'll get this error. I set the config to `django_celery_beat.schedulers.DatabaseScheduler` and it worked.

**Comment by mback2k** [comment]
@mheppner Thanks for the tip, setting `CELERY_BEAT_SCHEDULER` to `django_celery_beat.schedulers.DatabaseScheduler` solved the problem for me, too. But I will leave this issue open so that someone can decide if the docs should include this or not.

**Comment by wen96** [comment]
It happened to me too. So, +1 to include on docs.
