### ISSUE TITLE
ModuleNotFoundError: No module named 'django-celery-beat'

### ISSUE THREAD

**Issue by myt2000** [celery/django-celery-beat#635]
### Summary:

Include a *brief* description of the problem here, and fill out the version info below.  

* Celery Version: 5.2.7
* Celery-Beat Version: 2.4.0

### Exact steps to reproduce the issue:
1. Enter command  `celery -A efinancequotes.celery beat`
Error output
  File "E:\python3.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-celery-beat'

### Detailed information

Enter command `celery -A efinancequotes.celery worker` , it's OK.

django_celery_beat    has been added to  INSTALLED_APPS
![image](https://user-images.githubusercontent.com/26671449/223951494-83d8ffdf-f016-45f4-8318-4056fd17806b.png)

**Comment by myt2000** [comment]
celery beat v5.2.7 (dawn-chorus) is starting.
Traceback (most recent call last):
  File "E:\python3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\code\stock-analys-web\stock-analys-web\venv\Scripts\celery.exe\__main__.py", line 7, in <module>
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\__main__.py", line 15, in main
    sys.exit(_main())
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\bin\celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\bin\base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\bin\beat.py", line 72, in beat
    return beat().run()
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\apps\beat.py", line 77, in run
    self.start_scheduler()
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\apps\beat.py", line 96, in start_scheduler
    print(self.banner(service))
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\apps\beat.py", line 118, in banner
    c.reset(self.startup_info(service))),
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\apps\beat.py", line 128, in startup_info
    scheduler = service.get_scheduler(lazy=True)
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\celery\beat.py", line 670, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "E:\code\stock-analys-web\stock-analys-web\venv\lib\site-packages\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "E:\python3.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-celery-beat'

**Comment by myt2000** [comment]
settings write wrong 
CELERY_BEAT_SCHEDULER = 'django-celery-beat.schedulers.DatabaseScheduler'
modify
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
