### ISSUE TITLE
Microsecond interval does not work (app.conf.beat_schedule timedelta)

### ISSUE THREAD

**Issue by bestelde-chaos** [celery/django-celery-beat#673]
### Summary:

I am encountering an issue with scheduling tasks in Celery Beat with intervals in microseconds. When I try to configure tasks with microsecond intervals in the beat_schedule configuration, intervals less than 1 second are being rounded down to 0 seconds.

* Celery Version: 5.3.1
* Celery-Beat Version: 2.5.0

### Exact steps to reproduce the issue:
1. Create beat_schedule config
```python
app.conf.beat_schedule = {
    'my_task': {
        'task': 'app.periodic_jobs.my_task',
        'schedule': timedelta(microseconds=500_00),
    },
}
```
2. Run `django.setup()`
3. Check `django_celery_beat_intervalschedule` and `django_celery_beat_periodictask`

### Detailed information
If I try to use the example from the documentation, an error is thrown.
Code:
```python
if settings.IS_CELERY_RUN:
    django.setup()

schedule, created = IntervalSchedule.objects.get_or_create(
    every=settings.TASK_MICROSECONDS,
    period=IntervalSchedule.MICROSECONDS,
)

task = PeriodicTask.objects.create(
    interval=schedule,  # we created this above.
    name='My task',  # simply describes this periodic task.
    task='app.periodic_jobs.my_task',
)
```

Error:
```
schedule Error: Invalid value for '-A' / '--app':                                                                                                                          │
│ schedule Unable to load celery application.                                                                                                                                │
│ schedule While trying to load the module core the following error occurred:                                                                                                │
│ schedule Traceback (most recent call last):                                                                                                                                │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 389, in find_app                                                                       │
│ schedule     found = sym.app                                                                                                                                               │
│ schedule             ^^^^^^^                                                                                                                                               │
│ schedule AttributeError: module 'core' has no attribute 'app'                                                                                                              │
│ schedule                                                                                                                                                                   │
│ schedule During handling of the above exception, another exception occurred:                                                                                               │
│ schedule                                                                                                                                                                   │
│ schedule Traceback (most recent call last):                                                                                                                                │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 394, in find_app                                                                       │
│ schedule     found = sym.celery                                                                                                                                            │
│ schedule             ^^^^^^^^^^                                                                                                                                            │
│ schedule AttributeError: module 'core' has no attribute 'celery'                                                                                                           │
│ schedule                                                                                                                                                                   │
│ schedule During handling of the above exception, another exception occurred:                                                                                               │
│ schedule                                                                                                                                                                   │
│ schedule Traceback (most recent call last):                                                                                                                                │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 383, in find_app                                                                       │
│ schedule     sym = symbol_by_name(app, imp=imp)                                                                                                                            │
│ schedule           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                            │
│ schedule   File "/usr/local/lib/python3.11/site-packages/kombu/utils/imports.py", line 64, in symbol_by_name                                                               │
│ schedule     return getattr(module, cls_name) if cls_name else module                                                                                                      │
│ schedule            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                              │
│ schedule AttributeError: module 'core' has no attribute 'celery'                                                                                                           │
│ schedule                                                                                                                                                                   │
│ schedule During handling of the above exception, another exception occurred:                                                                                               │
│ schedule                                                                                                                                                                   │
│ schedule Traceback (most recent call last):                                                                                                                                │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 58, in convert
 schedule     return find_app(value)                                                                                                                                        │
│ schedule            ^^^^^^^^^^^^^^^                                                                                                                                        │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 401, in find_app                                                                       │
│ schedule     return find_app(                                                                                                                                              │
│ schedule            ^^^^^^^^^                                                                                                                                              │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 386, in find_app                                                                       │
│ schedule     sym = imp(app)                                                                                                                                                │
│ schedule           ^^^^^^^^                                                                                                                                                │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/utils/imports.py", line 104, in import_from_cwd                                                            │
│ schedule     return imp(module, package=package)                                                                                                                           │
│ schedule            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                           │
│ schedule   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module                                                                              │
│ schedule     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                   │
│ schedule            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                   │
│ schedule   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                                                                                                 │
│ schedule   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load                                                                                              │
│ schedule   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked                                                                                     │
│ schedule   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked                                                                                               │
│ schedule   File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                                                                         │
│ schedule   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                                    │
│ schedule   File "/app/src/core/celery.py", line 9, in <module>                                                                                                             │
│ schedule     from django_celery_beat.models import IntervalSchedule, PeriodicTask                                                                                          │
│ schedule   File "/usr/local/lib/python3.11/site-packages/django_celery_beat/models.py", line 9, in <module>                                                                │
│ schedule     import timezone_field                                                                                                                                         │
│ schedule   File "/usr/local/lib/python3.11/site-packages/timezone_field/__init__.py", line 1, in <module>                                                                  │
│ schedule     from timezone_field.fields import TimeZoneField                                                                                                               │
│ schedule   File "/usr/local/lib/python3.11/site-packages/timezone_field/fields.py", line 5, in <module>                                                                    │
│ schedule     from timezone_field.backends import TimeZoneNotFoundError, get_tz_backend                                                                                     │
│ schedule   File "/usr/local/lib/python3.11/site-packages/timezone_field/backends/__init__.py", line 5, in <module>                                                         │
│ schedule     USE_PYTZ_DEFAULT = getattr(conf.settings, "USE_DEPRECATED_PYTZ", VERSION < (4, 0))                                                                            │
│ schedule                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                            │
│ schedule   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 84, in __getattr__
│ schedule     self._setup(name)                                                                                                                                             │
│ schedule   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 65, in _setup                                                                      │
│ schedule     raise ImproperlyConfigured(                                                                                                                                   │
│ schedule django.core.exceptions.ImproperlyConfigured: Requested setting USE_DEPRECATED_PYTZ, but settings are not configured. You must either define the environment varia │
│ ble DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by bestelde-chaos** [comment]
![image](https://github.com/celery/django-celery-beat/assets/142424761/d51da5cd-5503-4c4c-ae51-b9b274dde60e)
![image](https://github.com/celery/django-celery-beat/assets/142424761/37661e27-6dbc-47e7-9818-7c25f77c2a72)

Works from admin

**Comment by bestelde-chaos** [comment]
![image](https://github.com/celery/django-celery-beat/assets/142424761/66e07f72-fed0-473a-89d4-299a168ac8d0)

Using beat_schedule (500_000 microseconds)

**Comment by auvipy** [comment]
schedule Error: Invalid value for '-A' / '--app':                                                                                                                          │
│ schedule Unable to load celery application.                                                                                                                                │
│ schedule While trying to load the module core the following error occurred:                                                                                                │
│ schedule Traceback (most recent call last):                                                                                                                                │
│ schedule   File "/usr/local/lib/python3.11/site-packages/celery/app/utils.py", line 389, in find_app                                                                       │
│ schedule     found = sym.app                                                                                                                                               │
│ schedule             ^^^^^^^                                                                                                                                               │
│ schedule AttributeError: module 'core' has no attribute 'app'

**Comment by auvipy** [comment]
can you help to reproduce it with new release?
