### ISSUE TITLE
Relation "django_celery_beat_periodictask" does not exist

### ISSUE THREAD

**Issue by mbaragiola** [celery/django-celery-beat#75]
Relevant versions:

```
python:3.5-slim
postgres:9.6-alpine
redis:4.0-alpine
django==1.11.4
celery==4.1.0
django-celery-beat==1.0.1
django-celery-results==1.0.1
```

Relevant `python manage.py migrate` output:

```
...
...
Applying django_celery_beat.0001_initial... OK
Applying django_celery_results.0001_initial... OK
...
...
```

Relevant `settings.py`:

```python
CELERY_REDIS_HOSTNAME = env('CELERY_REDIS_HOSTNAME', default='redis_celery')
CELERY_REDIS_PORT = env('CELERY_REDIS_PORT', default=6379)
CELERY_REDIS_DB = env('CELERY_REDIS_DB', default=0)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='')

if not CELERY_BROKER_URL:
    CELERY_BROKER_URL = 'redis://{hostname}:{port}/{db}'.format(
        hostname=CELERY_REDIS_HOSTNAME,
        port=CELERY_REDIS_PORT,
        db=CELERY_REDIS_DB
    )

CELERY_BROKER_POOL_LIMIT = 1
CELERY_BROKER_CONNECTION_TIMEOUT = 10

CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'UTC'

CELERY_DEFAULT_QUEUE = 'default'
CELERY_QUEUES = (
    Queue('default', Exchange('default'), routing_key='default')
)

CELERY_ALWAYS_EAGER = False
CELERY_ACKS_LATE = True
CELERY_TASK_PUBLISH_RETRY = True
CELERY_DISABLE_RATE_LIMITS = False

CELERY_RESULT_BACKEND = 'django-db'
```

`INSTALLED_APPS` of course has `django_celery_beat`, `django_celery_results` (that's why it is seen in the `migrate` output).

`project_name/celery.py`:

```python
import os
from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.local')

app = Celery('turnateme')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()

@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

Here's the relevant `docker-compose up` (local development) output:

```
djangodev_1        | System check identified no issues (0 silenced).
celerybeatdev_1    | Postgres is up - continuing...
celeryworkerdev_1  | Postgres is up - continuing...
celeryworkerdev_1  | /usr/local/lib/python3.5/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
celeryworkerdev_1  | absolutely not recommended!
celeryworkerdev_1  | 
celeryworkerdev_1  | Please specify a different user using the -u option.
celeryworkerdev_1  | 
celeryworkerdev_1  | User information: uid=0 euid=0 gid=0 egid=0
celeryworkerdev_1  | 
celeryworkerdev_1  |   uid=uid, euid=euid, gid=gid, egid=egid,
celeryworkerdev_1  |  
celeryworkerdev_1  |  -------------- default@4d8350ed217b v4.1.0 (latentcall)
celeryworkerdev_1  | ---- **** ----- 
celeryworkerdev_1  | --- * ***  * -- Linux-4.4.66-boot2docker-x86_64-with-debian-8.9 2017-08-12 20:11:55
celeryworkerdev_1  | -- * - **** --- 
celeryworkerdev_1  | - ** ---------- [config]
celeryworkerdev_1  | - ** ---------- .> app:         turnateme:0x7fdd92f53b70
celeryworkerdev_1  | - ** ---------- .> transport:   redis://redis_celery:6379/0
celeryworkerdev_1  | - ** ---------- .> results:     
celeryworkerdev_1  | - *** --- * --- .> concurrency: 1 (prefork)
celeryworkerdev_1  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celeryworkerdev_1  | --- ***** ----- 
celeryworkerdev_1  |  -------------- [queues]
celeryworkerdev_1  |                 .> default          exchange=default(direct) key=default
celeryworkerdev_1  |                 
celeryworkerdev_1  | 
celeryworkerdev_1  | [tasks]
celeryworkerdev_1  |   . billing.tasks.charge_period
celeryworkerdev_1  |   . billing.tasks.finish_period
celeryworkerdev_1  |   . billing.tasks.process_webhook_event
celeryworkerdev_1  |   . turnateme.celery.debug_task
celeryworkerdev_1  | 
celeryworkerdev_1  | [2017-08-12 20:11:55,228: INFO/MainProcess] Connected to redis://redis_celery:6379/0
celerybeatdev_1    | celery beat v4.1.0 (latentcall) is starting.
celerybeatdev_1    | __    -    ... __   -        _
celerybeatdev_1    | LocalTime -> 2017-08-12 20:11:55
celerybeatdev_1    | Configuration ->
celerybeatdev_1    |     . broker -> redis://redis_celery:6379/0
celerybeatdev_1    |     . loader -> celery.loaders.app.AppLoader
celerybeatdev_1    |     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
celerybeatdev_1    | 
celerybeatdev_1    |     . logfile -> [stderr]@%INFO
celerybeatdev_1    |     . maxinterval -> 5.00 seconds (5s)
celerybeatdev_1    | [2017-08-12 20:11:55,520: INFO/MainProcess] beat: Starting...
celerybeatdev_1    | [2017-08-12 20:11:55,521: INFO/MainProcess] Writing entries...
postgres_1         | ERROR:  relation "django_celery_beat_periodictask" does not exist at character 748
postgres_1         | STATEMENT:  SELECT "django_celery_beat_periodictask"."id", "django_celery_beat_periodictask"."name", "django_celery_beat_periodictask"."task", "django_celery_beat_periodictask"."interval_id", "django_celery_beat_periodictask"."crontab_id", "django_celery_beat_periodictask"."args", "django_celery_beat_periodictask"."kwargs", "django_celery_beat_periodictask"."queue", "django_celery_beat_periodictask"."exchange", "django_celery_beat_periodictask"."routing_key", "django_celery_beat_periodictask"."expires", "django_celery_beat_periodictask"."enabled", "django_celery_beat_periodictask"."last_run_at", "django_celery_beat_periodictask"."total_run_count", "django_celery_beat_periodictask"."date_changed", "django_celery_beat_periodictask"."description" FROM "django_celery_beat_periodictask" WHERE "django_celery_beat_periodictask"."enabled" = true
celerybeatdev_1    | [2017-08-12 20:11:55,538: CRITICAL/MainProcess] beat raised exception <class 'django.db.utils.ProgrammingError'>: ProgrammingError('relation "django_celery_beat_periodictask" does not exist\nLINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...\n                                                             ^\n',)
celerybeatdev_1    | Traceback (most recent call last):
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
celerybeatdev_1    |     return obj.__dict__[self.__name__]
celerybeatdev_1    | KeyError: 'scheduler'
celerybeatdev_1    | 
celerybeatdev_1    | During handling of the above exception, another exception occurred:
celerybeatdev_1    | 
celerybeatdev_1    | Traceback (most recent call last):
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
celerybeatdev_1    |     return self.cursor.execute(sql, params)
celerybeatdev_1    | psycopg2.ProgrammingError: relation "django_celery_beat_periodictask" does not exist
celerybeatdev_1    | LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...
celerybeatdev_1    |                                                              ^
celerybeatdev_1    | 
celerybeatdev_1    | 
celerybeatdev_1    | The above exception was the direct cause of the following exception:
celerybeatdev_1    | 
celerybeatdev_1    | Traceback (most recent call last):
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 107, in start_scheduler
celerybeatdev_1    |     service.start()
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 549, in start
celerybeatdev_1    |     humanize_seconds(self.scheduler.max_interval))
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
celerybeatdev_1    |     value = obj.__dict__[self.__name__] = self.__get(obj)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 593, in scheduler
celerybeatdev_1    |     return self.get_scheduler()
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 588, in get_scheduler
celerybeatdev_1    |     lazy=lazy,
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 179, in __init__
celerybeatdev_1    |     Scheduler.__init__(self, *args, **kwargs)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 206, in __init__
celerybeatdev_1    |     self.setup_schedule()
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 187, in setup_schedule
celerybeatdev_1    |     self.install_default_entries(self.schedule)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 280, in schedule
celerybeatdev_1    |     self._schedule = self.all_as_schedule()
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 193, in all_as_schedule
celerybeatdev_1    |     for model in self.Model.objects.enabled():
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
celerybeatdev_1    |     self._fetch_all()
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
celerybeatdev_1    |     self._result_cache = list(self._iterable_class(self))
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
celerybeatdev_1    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
celerybeatdev_1    |     raise original_exception
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
celerybeatdev_1    |     cursor.execute(sql, params)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
celerybeatdev_1    |     return super(CursorDebugWrapper, self).execute(sql, params)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
celerybeatdev_1    |     return self.cursor.execute(sql, params)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
celerybeatdev_1    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
celerybeatdev_1    |     raise value.with_traceback(tb)
celerybeatdev_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
celerybeatdev_1    |     return self.cursor.execute(sql, params)
celerybeatdev_1    | django.db.utils.ProgrammingError: relation "django_celery_beat_periodictask" does not exist
celerybeatdev_1    | LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...
celerybeatdev_1    |                                                              ^
celerybeatdev_1    | 
celerybeatdev_1    | [2017-08-12 20:11:55,540: WARNING/MainProcess] Traceback (most recent call last):
celerybeatdev_1    | [2017-08-12 20:11:55,540: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] return obj.__dict__[self.__name__]
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] KeyError
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] :
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] 'scheduler'
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] During handling of the above exception, another exception occurred:
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] Traceback (most recent call last):
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
celerybeatdev_1    | [2017-08-12 20:11:55,541: WARNING/MainProcess] return self.cursor.execute(sql, params)
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] psycopg2
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] .
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] ProgrammingError
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] :
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] relation "django_celery_beat_periodictask" does not exist
celerybeatdev_1    | LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...
celerybeatdev_1    |                                                              ^
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] The above exception was the direct cause of the following exception:
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] Traceback (most recent call last):
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] File "/usr/local/bin/celery", line 11, in <module>
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] sys.exit(main())
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
celerybeatdev_1    | [2017-08-12 20:11:55,542: WARNING/MainProcess] _main()
celerybeatdev_1    | [2017-08-12 20:11:55,543: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
celerybeatdev_1    | [2017-08-12 20:11:55,543: WARNING/MainProcess] cmd.execute_from_commandline(argv)
celerybeatdev_1    | [2017-08-12 20:11:55,543: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
celerybeatdev_1    | [2017-08-12 20:11:55,543: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
celerybeatdev_1    | [2017-08-12 20:11:55,544: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
celerybeatdev_1    | [2017-08-12 20:11:55,544: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
celerybeatdev_1    | [2017-08-12 20:11:55,544: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 480, in handle_argv
celerybeatdev_1    | [2017-08-12 20:11:55,544: WARNING/MainProcess] return self.execute(command, argv)
celerybeatdev_1    | [2017-08-12 20:11:55,544: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 412, in execute
celerybeatdev_1    | [2017-08-12 20:11:55,545: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
celerybeatdev_1    | [2017-08-12 20:11:55,545: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 285, in run_from_argv
celerybeatdev_1    | [2017-08-12 20:11:55,545: WARNING/MainProcess] sys.argv if argv is None else argv, command)
celerybeatdev_1    | [2017-08-12 20:11:55,545: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 368, in handle_argv
celerybeatdev_1    | [2017-08-12 20:11:55,545: WARNING/MainProcess] return self(*args, **options)
celerybeatdev_1    | [2017-08-12 20:11:55,545: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 244, in __call__
celerybeatdev_1    | [2017-08-12 20:11:55,546: WARNING/MainProcess] ret = self.run(*args, **kwargs)
celerybeatdev_1    | [2017-08-12 20:11:55,546: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/bin/beat.py", line 107, in run
celerybeatdev_1    | [2017-08-12 20:11:55,546: WARNING/MainProcess] return beat().run()
celerybeatdev_1    | [2017-08-12 20:11:55,546: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 79, in run
celerybeatdev_1    | [2017-08-12 20:11:55,546: WARNING/MainProcess] self.start_scheduler()
celerybeatdev_1    | [2017-08-12 20:11:55,547: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 107, in start_scheduler
celerybeatdev_1    | [2017-08-12 20:11:55,547: WARNING/MainProcess] service.start()
celerybeatdev_1    | [2017-08-12 20:11:55,547: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 549, in start
celerybeatdev_1    | [2017-08-12 20:11:55,547: WARNING/MainProcess] humanize_seconds(self.scheduler.max_interval))
celerybeatdev_1    | [2017-08-12 20:11:55,547: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
celerybeatdev_1    | [2017-08-12 20:11:55,547: WARNING/MainProcess] value = obj.__dict__[self.__name__] = self.__get(obj)
celerybeatdev_1    | [2017-08-12 20:11:55,547: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 593, in scheduler
celerybeatdev_1    | [2017-08-12 20:11:55,548: WARNING/MainProcess] return self.get_scheduler()
celerybeatdev_1    | [2017-08-12 20:11:55,548: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 588, in get_scheduler
celerybeatdev_1    | [2017-08-12 20:11:55,548: WARNING/MainProcess] lazy=lazy,
celerybeatdev_1    | [2017-08-12 20:11:55,548: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 179, in __init__
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] Scheduler.__init__(self, *args, **kwargs)
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/beat.py", line 206, in __init__
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] self.setup_schedule()
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 187, in setup_schedule
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] self.install_default_entries(self.schedule)
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 280, in schedule
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] self._schedule = self.all_as_schedule()
celerybeatdev_1    | [2017-08-12 20:11:55,549: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 193, in all_as_schedule
celerybeatdev_1    | [2017-08-12 20:11:55,550: WARNING/MainProcess] for model in self.Model.objects.enabled():
celerybeatdev_1    | [2017-08-12 20:11:55,550: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
celerybeatdev_1    | [2017-08-12 20:11:55,550: WARNING/MainProcess] self._fetch_all()
celerybeatdev_1    | [2017-08-12 20:11:55,550: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
celerybeatdev_1    | [2017-08-12 20:11:55,551: WARNING/MainProcess] self._result_cache = list(self._iterable_class(self))
celerybeatdev_1    | [2017-08-12 20:11:55,551: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
celerybeatdev_1    | [2017-08-12 20:11:55,551: WARNING/MainProcess] results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
celerybeatdev_1    | [2017-08-12 20:11:55,551: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
celerybeatdev_1    | [2017-08-12 20:11:55,560: WARNING/MainProcess] raise original_exception
celerybeatdev_1    | [2017-08-12 20:11:55,560: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
celerybeatdev_1    | [2017-08-12 20:11:55,561: WARNING/MainProcess] cursor.execute(sql, params)
celerybeatdev_1    | [2017-08-12 20:11:55,561: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
celerybeatdev_1    | [2017-08-12 20:11:55,561: WARNING/MainProcess] return super(CursorDebugWrapper, self).execute(sql, params)
celerybeatdev_1    | [2017-08-12 20:11:55,561: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
celerybeatdev_1    | [2017-08-12 20:11:55,561: WARNING/MainProcess] return self.cursor.execute(sql, params)
celerybeatdev_1    | [2017-08-12 20:11:55,562: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
celerybeatdev_1    | [2017-08-12 20:11:55,562: WARNING/MainProcess] six.reraise(dj_exc_type, dj_exc_value, traceback)
celerybeatdev_1    | [2017-08-12 20:11:55,562: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
celerybeatdev_1    | [2017-08-12 20:11:55,562: WARNING/MainProcess] raise value.with_traceback(tb)
celerybeatdev_1    | [2017-08-12 20:11:55,564: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
celerybeatdev_1    | [2017-08-12 20:11:55,564: WARNING/MainProcess] return self.cursor.execute(sql, params)
celerybeatdev_1    | [2017-08-12 20:11:55,564: WARNING/MainProcess] django.db.utils
celerybeatdev_1    | [2017-08-12 20:11:55,564: WARNING/MainProcess] .
celerybeatdev_1    | [2017-08-12 20:11:55,564: WARNING/MainProcess] ProgrammingError
celerybeatdev_1    | [2017-08-12 20:11:55,564: WARNING/MainProcess] :
celerybeatdev_1    | [2017-08-12 20:11:55,564: WARNING/MainProcess] relation "django_celery_beat_periodictask" does not exist
celerybeatdev_1    | LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...
celerybeatdev_1    |                                                              ^
celerybeatdev_1    | [2017-08-12 20:11:55,564: INFO/MainProcess] Writing entries...
turnateme_celerybeatdev_1 exited with code 1
celeryworkerdev_1  | [2017-08-12 20:11:55,240: INFO/MainProcess] mingle: searching for neighbors
celeryworkerdev_1  | [2017-08-12 20:11:56,273: INFO/MainProcess] mingle: all alone
celeryworkerdev_1  | [2017-08-12 20:11:56,284: WARNING/MainProcess] /usr/local/lib/python3.5/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
```

If anything else is needed to further debug this, please let me know. Thank you in advance.

**Comment by mbaragiola** [comment]
Apparently some `postgres` environment weren't properly set when instantiating custom `django` image to run Celery, so it didn't connect to the database that it should. If someone encounters this, make sure you have `POSTGRES_USER`, `POSTGRES_DB` and `POSTGRES_PASSWORD` set on your Celery instances.

**Comment by mav-erick** [comment]
Hey, I am facing the same problem.. How did you solve this?

**Comment by mbaragiola** [comment]
Yes @mav-erick, try doing that. Are you running dockerized instances?

**Comment by mav-erick** [comment]
@mbaragiola I was able to resolve this. It was a different issue. Thanks for the reply.

**Comment by dvgdex** [comment]
> @mbaragiola I was able to resolve this. It was a different issue. Thanks for the reply.

May i know how did you solve this ?
I encounter the same issue using docker to run celery

**Comment by mbaragiola** [comment]
> > @mbaragiola I was able to resolve this. It was a different issue. Thanks for the reply.
> 
> May i know how did you solve this ?
> I encounter the same issue using docker to run celery

Make sure you are running with the same POSTGRES_USER that you initialized the docker with. I don't remember much else, sorry

**Comment by dvgdex** [comment]
> > > @mbaragiola I was able to resolve this. It was a different issue. Thanks for the reply.
> > 
> > 
> > May i know how did you solve this ?
> > I encounter the same issue using docker to run celery
> 
> Make sure you are running with the same POSTGRES_USER that you initialized the docker with. I don't remember much else, sorry

I manually run "python manage.my migrate" , then it works.  Thanks for your reply.

**Comment by bluegrounds** [comment]
It's kinda unrelated but since google search leads here, I'll share what happened with me for anyone else running into this.

I ran into this because I was also using [django-tenants-celery-beat](https://github.com/QuickRelease/django-tenants-celery-beat) which modifies how this library works to make it compatible with django-tenants, and it has a model `PeriodicTaskTenantLink` that has a foreign key to `settings.TENANT_MODEL`. But since the tenant model depends on the consumer of that library, the migration file can **only be created after the tenant model is known**. Which means you have to manually run `makemigrations` to create a migration file (in that library's folder btw 😕) to create the table needed.

After that you can run migrations, the table PeriodicTaskTenantLink gets created with proper foreign keys and everything works fine.
